[Intangible Textual Heritage](../../index)  [Islam](../index.md) 

------------------------------------------------------------------------

The HADÎQATU' L-<u>H</u>AQÎQAT

#### (THE ENCLOSED GARDEN OF THE TRUTH)

### by HAKÎM ABÛ' L-MAJD MAJDÛD SANÂ'Î OF <u>GH</u>AZNA.

#### EDITED AND TRANSLATED BY J. STEPHENSON,

#### \[1910\]

------------------------------------------------------------------------

Technical Note: Due to the limitations of optical character recognition,
the extensive footnotes in the body of the text had to be omitted; I
have manually inserted a few parenthetical notes, particularly the
references to the Qur'an. In addion, Arabic characters are written using
\# signs throughout; I may add Unicode entities at some point.

--JBH.

[Title Page](egt00.md)  
[Preface.](egt01.md)  
[Abbreviations.](egt02.md)  
[Introduction.](egt03.md)  
[I.--Life of the Author.](egt04.md)  
[II.--Manuscripts and Lithographs.](egt05.md)  
[III.--History of the Text.](egt06.md)  
[IV.--The Commentators.](egt07.md)  
[V.--The <u>H</u>adÎqatu'l-haqîqat.](egt08.md)  
[VI.--Sanâ'î's Preface.](egt09.md)  
[The First Book of the <u>H</u>adîqatu'-l-H<u>a</u>qîqat of
Sanâ'î.](egt10.md)  
[ON THE KNOWLEDGE OF GOD.](egt11.md)  
[ON THE ASSERTION OF THE UNITY.](egt12.md)  
[ON GOD AS FIRST CAUSE.](egt13.md)  
[ON PURITY OF HEART.](egt14.md)  
[ON THE BLIND MEN AND THE AFFAIR OF THE ELEPHANT.](egt15.md)  
[ON THE ABOVE ALLEGORY.](egt16.md)  
[OF THOSE WHO HEED NOT.](egt17.md)  
[ON THE STEPS OF ASCENT.](egt18.md)  
[ON THE PROTECTION AND GUARDIANSHIP OF GOD.](egt19.md)  
[THE PARABLE OF THOSE WHO GIVE ALMS.](egt20.md)  
[ON THE CAUSE OF OUR MAINTENANCE.](egt21.md)  
[OF THE RIGHT GUIDANCE](egt22.md)  
[ON THE SURRENDER OF THE SELF.](egt23.md)  
[IN HIS MAGNIFICATION.](egt24.md)  
[ON THE EARNEST STRIVING.](egt25.md)  
[OF THE TRAVELLER ON THE PATH.](egt26.md)  
[ON BEING SILENT.](egt27.md)  
[THE PARABLE OF THOSE WHO HEED NOT.](egt28.md)  
[THE PARABLE OF THE EYE OF THE SQUINT-EYED.](egt29.md)  
[AGAIN THE PARABLE OF THOSE WHO HEED NOT.](egt30.md)  
[IN PRAISE OF HIS OMNIPOTENCE.](egt31.md)  
[ON THE PROVERBS AND ADMONITIONS 'POVERTY IS BLACKNESS OF THE FACE' (THE
RECITAL OF PROVERBS IS THE BEST OF DISCOURSES) AND 'THE WORLD IS A HOUSE
OF DEPARTURE AND CHANGING AFFAIRS AND MIGRATION.'](egt32.md)  
[ON THE NEED OF GOD, AND INDEPENDENCE OF ALL BESIDE HIM.](egt33.md)  
[ON SELF-ABASEMENT AND HUMILITY.](egt34.md)  
[ON THE JUSTICE OF THE PRINCE AND THE SECURITY OF HIS
SUBJECTS.](egt35.md)  
[ON CELEBRATING THE PRAISE OF GOD.](egt36.md)  
[CONCERNING THE PIOUS DISCIPLE AND THE GREAT MASTER.](egt37.md)  
[CONCERNING THE HOUSE OF DECEPTION.](egt38.md)  
[ON GIVING THANKS.](egt39.md)  
[ON HIS WRATH AND HIS KINDNESS.](egt40.md)  
[ON HIS, OMNISCIENCE, AND HIS KNOWLEDGE OF THE MINDS OF MEN.](egt41.md)  
[CONCERNING HIS BENEFICENCE,--AND VERILY HE IS THE PROVIDER OF
PROVISIONS.](egt42.md)  
[A STORY.](egt43.md)  
[A STORY.](egt44.md)  
[ON THE DESIRE FOR GOD.](egt45.md)  
[ON AFFECTION AND ISOLATION.](egt46.md)  
[ON RENUNCIATION AND STRENUOUS ENDEAVOUR.](egt47.md)  
[ON FOLLOWING THE PATH OF THE HEREAFTER.](egt48.md)  
[OF THE LEARNED MAN AND THE FOOL.](egt49.md)  
[A STORY.](egt50.md)  
[ON TRUST IN GOD.](egt51.md)  
[ON THE TRUST IN GOD SHOWN BY OLD WOMEN.](egt52.md)  
[ON THE KALIMA.](egt53.md)  
[ON THE INTERPRETATION OF THE DREAM.](egt54.md)  
[ON DREAMS OF VESSELS AND GARMENTS.](egt55.md)  
[ON DREAMS OF HANDICRAFTSMEN.](egt56.md)  
[ON DREAMS OF BEASTS.](egt57.md)  
[ON DREAMS OF WILD ANIMALS.](egt58.md)  
[ON DREAMS OF LIGHTS AND STARS.](egt59.md)  
[ON THE INCOMPATIBILITY OF THE TWO ABODES.](egt60.md)  
[THE PARABLE OF THE SCHOOLBOYS.](egt61.md)  
[ON STRIVING IN GOD'S PATH.](egt62.md)  
[ON CHARITY AND GIFTS.](egt63.md)  

OF THE STORY OF QAIS IBN \`Â

<u>S</u>IM.  
[ON INTIMATE FRIENDSHIP AND ATTACHMENT.](egt65.md)  
[HE WHO IS INDIFFERENT TO THE WORLD FINDS A KINGDOM THAT SHALL NOT WANE.
(Qur. 20:118)](egt66.md)  
[ON THE ASCETICISM OF THE ASCETIC.](egt67.md)  
[ON THE LOVE OF THE WORLD AND THE MANNER OF THE PEOPLE OF IT.](egt68.md)  
[OF ADDRESSES TO GOD, AND SELF-ABASEMENT, AND HUMILITY.](egt69.md)  
[ON THE PARTICIPATION OF THE HEART IN PRAYER.](egt70.md)  
[ON FAILURE TO PRAY ARIGHT](egt71.md)  
[ON LAUD AND PRAISE.](egt72.md)  
[ON POVERTY AND PERPLEXITY.](egt73.md)  
[ON BEING GLAD IN GOD MOST HIGH, AND HUMBLING ONESELF BEFORE
HIM](egt74.md)  
[ON HIS KINDNESS AND BOUNTY.](egt75.md)  
[ON TURNING TO GOD.](egt76.md)  
[HE WHO TRUSTS IN HIS SUBMISSION SUFFERS A MANIFEST HURT.](egt77.md)  
[ON DEVOTION TO GOD.](egt78.md)  
[OF HIS MERCY.](egt79.md)  
[OF HIM WHO FEEDS ME AND GIVES ME DRINK.](egt80.md)  
[OF THE MULTITUDE; THEY ARE LIKE CATTLE--NAY. THEY ARE MORE
ERRING.](egt81.md)  
[ON THE DESIRE FOR GOD](egt82.md)  
[ON HIS DECREE AND ORDINANCE AND HIS CREATIVE POWER.](egt83.md)  
[TO REMEMBER THE WORDS OF THE ALL-KNOWING LORD](egt84.md)  
[ON THE GLORY OF THE QUR'ÂN.](egt85.md)  
[OF THE RECITAL OF THE SECRET OF THE QUR'ÂN.](egt86.md)  
[IN THE RECITAL OF THE MIRACLE WROUGHT BY THE QUR'ÂN.](egt87.md)  
[OF THE GUIDANCE OF THE QUR'ÂN.](egt88.md)  
[ON THE GREATNESS OF THE QUR'ÂN,--VERILY IT CONSISTS NOT IN ITS DIVISION
INTO 'TENS' AND 'FIVES.'](egt89.md)  
[ON THE ALLEGATIONS BROUGHT FORWARD BY THE WORD OF GOD.](egt90.md)  
[ON THE SWEETNESS. OF THE QUR'ÂN.](egt91.md)  
[ON THE HEARING OF THE QUR'ÂN.](egt92.md)  
[THE COMPARISON OF THE CREATION OF ADAM AND OF JESUS SON OF MARY (ON
BOTH OF WHOM BE PEACE!).](egt93.md)  
[TO COMMEMORATE THE PROPHETS IS BETTER THAN SPEAKING OF FOOLS.](egt94.md)  
