[![](../../cdshop/ithlogo.png)](../../index.md)  
[Intangible Textual Heritage](../../index)  [Esoteric](../index.md) 
[Index](index)  [Previous](pnm02)  [Next](pnm04.md) 

------------------------------------------------------------------------

[Buy this Book at
Amazon.com](https://www.amazon.com/exec/obidos/ASIN/B002A9JP00/internetsacredte.md)

------------------------------------------------------------------------

[![](img/tease.jpg)](index.md)  
*The Philosophy of Natural Magic*, by Henry Cornelius Agrippa, L. W. de
Laurence ed. \[1913\], at Intangible Textual Heritage

------------------------------------------------------------------------

<span id="page_7">p. 7</span>

### TABLE OF CONTENTS.

<div align="center">

|                                                                                                                                                                                                                                                                 |                           |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------|
| **INTRODUCTORY.**                                                                                                                                                                                                                                               |                           |
| <span class="smallcaps">Editor's Preface</span>                                                                                                                                                                                                                 | [15](pnm05.htm#page_15.md)   |
| <span class="smallcaps">Early Life of Agrippa</span>                                                                                                                                                                                                            | [17](pnm06.htm#page_17.md)   |
| <span class="smallcaps">Cornelius Agrippa to the Reader</span>                                                                                                                                                                                                  | [27](pnm07.htm#page_27.md)   |
| <span class="smallcaps">Agrippa to Trithemius</span>                                                                                                                                                                                                            | [30](pnm08.htm#page_30.md)   |
| <span class="smallcaps">Trithemius to Agrippa</span>                                                                                                                                                                                                            | [33](pnm09.htm#page_33.md)   |
|                                                                                                                                                                                                                                                                 |                           |
| **THE PHILOSOPHY OF NATURAL MAGIC**                                                                                                                                                                                                                             |                           |
| <span class="smallcaps">Chapter</span> I. How Magicians Collect Virtues from the Three-fold World, is Declared in these Three Books                                                                                                                             | [37](pnm10.htm#page_37.md)   |
| <span class="smallcaps">Chapter</span> II. What Magic Is, What are the Parts thereof, and How the Professors thereof must be Qualified                                                                                                                          | [38](pnm10.htm#page_38.md)   |
| <span class="smallcaps">Chapter</span> III. Of the Four Elements, their Qualities, and Mutual Mixtions                                                                                                                                                          | [42](pnm11.htm#page_42.md)   |
| <span class="smallcaps">Chapter</span> IV. Of a Three-fold Consideration of the Elements                                                                                                                                                                        | [44](pnm12.htm#page_44.md)   |
| <span class="smallcaps">Chapter</span> V. Of the Wonderful Natures of Fire and Earth                                                                                                                                                                            | [45](pnm13.htm#page_45.md)   |
| <span class="smallcaps">Chapter</span> VI. Of the Wonderful Natures of Water, Air and Winds                                                                                                                                                                     | [48](pnm14.htm#page_48.md)   |
| <span class="smallcaps">Chapter</span> VII. Of the Kinds of Compounds, what Relation they stand in to the Elements, and what Relation there is betwixt the Elements themselves and the Soul, Senses and Dispositions of Men                                     | [56](pnm15.htm#page_56.md)   |
| <span id="page_8">p. 8</span>                                                                                                                                                                                                                                   |                           |
| <span class="smallcaps">Chapter</span> VIII. How the Elements are in the Heavens, in Stars, in Devils, in Angels, and, lastly, in God himself                                                                                                                   | [58](pnm16.htm#page_58.md)   |
| <span class="smallcaps">Chapter</span> IX. Of the Virtues of things Natural, depending immediately upon Elements                                                                                                                                                | [61](pnm17.htm#page_61.md)   |
| <span class="smallcaps">Chapter</span> X. Of the Occult Virtues of Things                                                                                                                                                                                       | [62](pnm18.htm#page_62.md)   |
| <span class="smallcaps">Chapter</span> XI. How Occult Virtues are Infused into the several kinds of Things by Ideas, through the Help of the Soul of the World, and Rays of the Stars; and what Things abound most with this Virtue                             | [65](pnm20.htm#page_65.md)   |
| <span class="smallcaps">Chapter</span> XII. How it is that Particular Virtues are Infused into Particular Individuals, even of the same Species                                                                                                                 | [67](pnm21.htm#page_67.md)   |
| <span class="smallcaps">Chapter</span> XIII. Whence the Occult Virtues of Things Proceed                                                                                                                                                                        | [68](pnm21.htm#page_68.md)   |
| <span class="smallcaps">Chapter</span> XIV. Of the Spirit of the World, What It Is and how by way of medium It Unites occult Virtues to their Subjects                                                                                                          | [72](pnm23.htm#page_72.md)   |
| <span class="smallcaps">Chapter</span> XV. How we must Find Out and Examine the Virtues of Things by way of Similitude                                                                                                                                          | [74](pnm23.htm#page_74.md)   |
| <span class="smallcaps">Chapter</span> XVI. How the Operations of several Virtues Pass from one thing into another, and are Communicated one to the other                                                                                                       | [77](pnm25.htm#page_77.md)   |
| <span class="smallcaps">Chapter</span> XVII. How by Enmity and Friendship the Virtues of things are to be Tried and Found Out                                                                                                                                   | [78](pnm25.htm#page_78.md)   |
| <span class="smallcaps">Chapter</span> XVIII. Of the Inclinations of Enmities                                                                                                                                                                                   | [81](pnm26.htm#page_81.md)   |
| <span class="smallcaps">Chapter</span> XIX. How the Virtues of Things are to be Tried and Found Out, which are in them Specifically, or in any one Individual by way of Special Gift                                                                            | [85](pnm28.htm#page_85.md)   |
| <span class="smallcaps">Chapter</span> XX. The Natural Virtues are in borne Things throughout their Whole Substance, and in other Things in Certain Parts and Members                                                                                           | [86](pnm29.htm#page_86.md)   |
| <span id="page_9">p. 9</span>                                                                                                                                                                                                                                   |                           |
| <span class="smallcaps">Chapter</span> XXI. Of the Virtues of Things which are in them only in their Life Time, and Such as Remain in them even After their Death                                                                                               | [88](pnm29.htm#page_88.md)   |
| <span class="smallcaps">Chapter</span> XXII. How Inferior Things are Subjected to Superior Bodies, and how the Bodies, Actions, and Dispositions of Men are Ascribed to Stars and Signs                                                                         | [91](pnm30.htm#page_91.md)   |
| <span class="smallcaps">Chapter</span> XXIII. How we shall Know what Stars Natural Things are Under, and what Things are Under the Sun, which are called Solary                                                                                                 | [95](pnm31.htm#page_95.md)   |
| <span class="smallcaps">Chapter</span> XXIV. What Things are Lunary, or Under the Power of the Moon                                                                                                                                                             | [99](pnm32.htm#page_99.md)   |
| <span class="smallcaps">Chapter</span> XXV. What Things are Saturnine, or Under the Power of Saturn                                                                                                                                                             | [101](pnm33.htm#page_101.md) |
| <span class="smallcaps">Chapter</span> XXVI. What Things are Under the Power of Jupiter, and are called Jovial                                                                                                                                                  | [104](pnm34.htm#page_104.md) |
| <span class="smallcaps">Chapter</span> XXVII. What Things are Under the Power of Mars, and are called Martial                                                                                                                                                   | [105](pnm35.htm#page_105.md) |
| <span class="smallcaps">Chapter</span> XXVIII. What Things are Under the Power of Venus, and are called Venereal                                                                                                                                                | [106](pnm36.htm#page_106.md) |
| <span class="smallcaps">Chapter</span> XXIX. What Things are Under the Power of Mercury, and are called Mercurial                                                                                                                                               | [107](pnm37.htm#page_107.md) |
| <span class="smallcaps">Chapter</span> XXX. That the Whole Sublunary World, and those Things which are in It, are Distributed to Planets                                                                                                                        | [108](pnm38.htm#page_108.md) |
| <span class="smallcaps">Chapter</span> XXXI. How Provinces and Kingdoms are Distributed to Planets                                                                                                                                                              | [109](pnm39.htm#page_109.md) |
| <span class="smallcaps">Chapter</span> XXXII. What Things are Under the Signs, the Fixed Stars, and their Images                                                                                                                                                | [111](pnm41.htm#page_111.md) |
| <span class="smallcaps">Chapter</span> XXXIII. The Seals and Characters of Natural Things                                                                                                                                                                       | [114](pnm41.htm#page_114.md) |
| <span id="page_10">p. 10</span>                                                                                                                                                                                                                                 |                           |
| <span class="smallcaps">Chapter</span> XXXIV. How, by Natural Things and their Virtues, we may Draw Forth and Attract the Influences and Virtues of Celestial Bodies                                                                                            | [118](pnm42.htm#page_118.md) |
| <span class="smallcaps">Chapter</span> XXXV. Of the Mixtions of Natural Things, one with another, and their Benefit                                                                                                                                             | [119](pnm43.htm#page_119.md) |
| <span class="smallcaps">Chapter</span> XXXVI. Of the Union of Mixed Things, and the Introduction of a More Noble Form, and the Senses of Life                                                                                                                   | [121](pnm44.htm#page_121.md) |
| <span class="smallcaps">Chapter</span> XXXVII. How, by some certain Natural and Artificial Preparations, We May Attract certain Celestial and Vital Gifts                                                                                                       | [123](pnm45.htm#page_123.md) |
| <span class="smallcaps">Chapter</span> XXXVIII. How We May Draw not only Celestial and Vital but also certain Intellectual and Divine Gifts from Above                                                                                                          | [125](pnm46.htm#page_125.md) |
| <span class="smallcaps">Chapter</span> XXXIX. That We May, by some certain Matters of the World, Stir Up the Gods of the World and their Ministering Spirits                                                                                                    | [127](pnm47.htm#page_127.md) |
| <span class="smallcaps">Chapter</span> XL. Of Bindings; what Sort they are of, and in what Ways they are wont to be Done                                                                                                                                        | [128](pnm48.htm#page_128.md) |
| <span class="smallcaps">Chapter</span> XLI. Of Sorceries, and their Power                                                                                                                                                                                       | [129](pnm49.htm#page_129.md) |
| <span class="smallcaps">Chapter</span> XLII. Of the Wonderful Virtues of some Kinds of Sorceries                                                                                                                                                                | [131](pnm50.htm#page_131.md) |
| <span class="smallcaps">Chapter</span> XLIII. Of Perfumes or Suffumigations; their Manner and Power                                                                                                                                                             | [136](pnm51.htm#page_136.md) |
| <span class="smallcaps">Chapter</span> XLIV. The Composition of some Fumes appropriated to the Planets                                                                                                                                                          | [139](pnm52.htm#page_139.md) |
| <span class="smallcaps">Chapter</span> XLV. Of Collyries, Unctions, Love-Medicines, and their Virtues                                                                                                                                                           | [141](pnm53.htm#page_141.md) |
| <span class="smallcaps">Chapter</span> XLVI. Of Natural Alligations and Suspensions                                                                                                                                                                             | [144](pnm55.htm#page_144.md) |
| <span class="smallcaps">Chapter</span> XLVII. Of Magical Rings and their Compositions                                                                                                                                                                           | [146](pnm56.htm#page_146.md) |
| <span id="page_11">p. 11</span>                                                                                                                                                                                                                                 |                           |
| <span class="smallcaps">Chapter</span> XLVIII. Of the Virtue of Places, and what Places are Suitable to every Star                                                                                                                                              | [148](pnm57.htm#page_148.md) |
| <span class="smallcaps">Chapter</span> XLIX. Of Light, Colors, Candles and Lamps, and to what Stars, Houses and Elements several Colors are Ascribed                                                                                                            | [151](pnm58.htm#page_151.md) |
| <span class="smallcaps">Chapter</span> L. Of Fascination, and the Art thereof                                                                                                                                                                                   | [154](pnm58.htm#page_154.md) |
| <span class="smallcaps">Chapter</span> LI. Of certain Observations, Producing wonderful Virtues                                                                                                                                                                 | [156](pnm59.htm#page_156.md) |
| <span class="smallcaps">Chapter</span> LII. Of the Countenance and Gesture, the Habit and the Figure of the Body, and to what Stars any of these do Answer; whence Physiognomy, and Metoposcopy, and Chiromancy, Arts of Divination, have their Grounds         | [159](pnm60.htm#page_159.md) |
| <span class="smallcaps">Chapter</span> LIII. Of Divination, and the Kinds thereof                                                                                                                                                                               | [162](pnm61.htm#page_162.md) |
| <span class="smallcaps">Chapter</span> LIV. Of divers certain Animals, and other things, which have a Signification in Auguries                                                                                                                                 | [165](pnm62.htm#page_165.md) |
| <span class="smallcaps">Chapter</span> LV. How Auspicias are Verified by the Light of Natural Instinct, and of some Rules of Finding of It Out                                                                                                                  | [173](pnm64.htm#page_173.md) |
| <span class="smallcaps">Chapter</span> LVI. Of the Soothsayings of Flashes and Lightnings, and how Monstrous and Prodigious Things are to be Interpreted                                                                                                        | [178](pnm64.htm#page_178.md) |
| <span class="smallcaps">Chapter</span> LVII. Of Geomancy, Hydromancy, Aeromancy, and Pyromancy, Four Divinations of Elements                                                                                                                                    | [181](pnm66.htm#page_181.md) |
| <span class="smallcaps">Chapter</span> LVIII. Of the Reviving of the Dead, and of Sleeping or Hibernating (wanting victuals) Many Years together                                                                                                                | [183](pnm66.htm#page_183.md) |
| <span class="smallcaps">Chapter</span> LIX. Of Divination by Dreams                                                                                                                                                                                             | [188](pnm68.htm#page_188.md) |
| <span class="smallcaps">Chapter</span> LX. Of Madness, and Divinations which are made when men are awake, and of the Power of a Melancholy Humor, by which Spirits are sometimes induced into Men's Bodies                                                      | [189](pnm68.htm#page_189.md) |
| <span id="page_12">p. 12</span>                                                                                                                                                                                                                                 |                           |
| <span class="smallcaps">Chapter</span> LXI. Of the Forming of Men, of the External Senses, also those Inward, and the Mind; and of the Three-fold Appetite of the Soul, and Passions of the Will                                                                | [193](pnm69.htm#page_193.md) |
| <span class="smallcaps">Chapter</span> LXII. Of the Passions of the Mind, their Original Source, Differences, and Kinds                                                                                                                                         | [197](pnm70.htm#page_197.md) |
| <span class="smallcaps">Chapter</span> LXIII. How the Passions of the Mind change the proper Body by changing its Accidents and moving the Spirit                                                                                                               | [199](pnm72.htm#page_199.md) |
| <span class="smallcaps">Chapter</span> LXIV. How the Passions of the Mind change the Body by way of Imitation from some Resemblance; of the Transforming and Translating of Men, and what Force the Imaginative Power hath, not only over the Body but the Soul | [201](pnm73.htm#page_201.md) |
| <span class="smallcaps">Chapter</span> LXV. How the Passions of the Mind can Work of themselves upon Another's Body                                                                                                                                             | [204](pnm74.htm#page_204.md) |
| <span class="smallcaps">Chapter</span> LXVI. That the Passions of the Mind are Helped by a Celestial Season, and how Necessary the Constancy of the Mind is in every Work                                                                                       | [206](pnm74.htm#page_206.md) |
| <span class="smallcaps">Chapter</span> LXVII. How the Mind of Man may be Joined with the Mind of the Stars, and Intelligences of the Celestials, and, together with them, Impress certain wonderful Virtues upon inferior Things                                | [208](pnm76.htm#page_208.md) |
| <span class="smallcaps">Chapter</span> LXVIII. How our Mind can Change and Bind inferior Things to the Ends which we Desire                                                                                                                                     | [209](pnm76.htm#page_209.md) |
| <span class="smallcaps">Chapter</span> LXIX. Of Speech, and the Occult Virtue of Words                                                                                                                                                                          | [210](pnm77.htm#page_210.md) |
| <span class="smallcaps">Chapter</span> LXX. Of the Virtue of Proper Names                                                                                                                                                                                       | [212](pnm79.htm#page_212.md) |
| <span class="smallcaps">Chapter</span> LXXI. Of many Words joined together, as in Sentences and Verses; and of the Virtues and Astrictions of Charms                                                                                                            | [214](pnm80.htm#page_214.md) |
| <span class="smallcaps">Chapter</span> LXXII. Of the wonderful Power of Enchantments                                                                                                                                                                            | [216](pnm80.htm#page_216.md) |
| <span id="page_13">p. 13</span>                                                                                                                                                                                                                                 |                           |
| <span class="smallcaps">Chapter</span> LXXIII. Of the Virtue of Writing, and of Making Imprecations, and Inscriptions                                                                                                                                           | [218](pnm81.htm#page_218.md) |
| <span class="smallcaps">Chapter</span> LXXIV. Of the Proportion, Correspondency, and Reduction of Letters to the Celestial Signs and Planets, According to various Tongues, and a Table thereof                                                                 | [219](pnm82.htm#page_219.md) |
|                                                                                                                                                                                                                                                                 |                           |
| **BY HENRY MORLEY.**                                                                                                                                                                                                                                            |                           |
| Criticism on Agrippa's Natural Magic                                                                                                                                                                                                                            | [224](pnm84.htm#page_224.md) |
| Agrippa and the Rosicrucians                                                                                                                                                                                                                                    | [226](pnm85.htm#page_226.md) |
| Exposition of the Cabala                                                                                                                                                                                                                                        | [234](pnm85.htm#page_234.md) |
| The Mirific Word                                                                                                                                                                                                                                                | [245](pnm86.htm#page_245.md) |
| New Table of the Cabala and Tarot (specially compiled)                                                                                                                                                                                                          | [246](pnm87.htm#page_246.md) |
| Reuchlin the Mystic                                                                                                                                                                                                                                             | [250](pnm87.htm#page_250.md) |
| Agrippa Expounds Reuchlin                                                                                                                                                                                                                                       | [258](pnm89.htm#page_258.md) |
| The Nobility of Woman                                                                                                                                                                                                                                           | [261](pnm90.htm#page_261.md) |
| Order of the Empyrean Heaven                                                                                                                                                                                                                                    | [275](pnm90.htm#page_275.md) |
| Symbols of the Alchemists                                                                                                                                                                                                                                       | [282](pnm92.htm#page_282.md) |
|                                                                                                                                                                                                                                                                 |                           |
| **BY DR. L. W. DE LAURENCE.**                                                                                                                                                                                                                                   |                           |
| The Eternal Principle                                                                                                                                                                                                                                           | [286](pnm94.htm#page_286.md) |
| A Message To Mystics, The Magic Mirror                                                                                                                                                                                                                          | [288](pnm95.htm#page_288.md) |

</div>

 

#### ILLUSTRATIONS AND ETCHINGS.

<div align="center">

|                                               |                                                                                 |
|-----------------------------------------------|---------------------------------------------------------------------------------|
| Title Page of 1651 Edition                    | [36](pnm10.htm#page_36.md)                                                         |
| Grand Solar Man                               | [90](pnm30.htm#page_90.md)                                                         |
| Calamus                                       | [98](pnm32.htm#page_98.md)                                                         |
| Characters of Nature                          | [116](pnm42.htm#page_116.md)                                                       |
| Divine Letters                                | [117](pnm42.htm#page_117.md)                                                       |
| Cabalistical Table of Co-ordinate Characters  | [223](pnm83.htm#page_223.md)                                                       |
| Tree of the Cabala (three full-page etchings) | [239](pnm86.htm#page_239), [241](pnm86.htm#page_241), [243](pnm86.htm#page_243.md) |
| The Empyrean Heaven                           | [274](pnm90.htm#page_274.md)                                                       |
| Rosicrucian Symbol of the Spirit of Nature    | [277](pnm91.htm#page_277.md)                                                       |
| Symbols of the Alchemists                     | [283](pnm92.htm#page_283.md)                                                       |

</div>

------------------------------------------------------------------------

[Next: Sublime Occult Philosophy](pnm04.md)
