[Intangible Textual Heritage](../../index)  [Africa](../index.md) 
[Index](index)  [Previous](yor00)  [Next](yor02.md) 

------------------------------------------------------------------------

# CONTENTS.

CHAPTER I. INTRODUCTORY

CHAPTER II. CHIEF GODS

CHAPTER III. MINOR GODS

CHAPTER IV. REMARKS ON THE FOREGOING

CHAPTER V. PRIESTS AND WORSHIP

CHAPTER VI. EGUNGUN, ORO, ABIKU, AND VARIOUS SUPERSTITIONS

CHAPTER VII. THE INDWELLING SPIRITS AND SOULS OF MEN

CHAPTER VIII. MEASUREMENTS OF TIME

CHAPTER IX. CEREMONIES AT BIRTH, MARRIAGE, AND DEATH

CHAPTER X. SYSTEM OF GOVERNMENT

CHAPTER XI. LAWS AND CUSTOMS

CHAPTER XII. LANGUAGE

CHAPTER XIII. PROVERBS

CHAPTER XIV. FOLK-LORE TALES

CHAPTER XV. CONCLUSION

APPENDIX

 

 

------------------------------------------------------------------------

[Next: Chapter I: Introductory.](yor02.md)
