[![](../../../cdshop/ithlogo.png)](../../../index.md)  
[Intangible Textual Heritage](../../../index.md)  [Legends &
Sagas](../../index)  [England](../index)  [Index](index.md) 
[Previous](str14.md) 

------------------------------------------------------------------------

[![](img/tease.jpg)](index.md)  
*Stonehenge, A Temple Restor'd to the British Druids*, by William
Stukeley, \[1740\], at Intangible Textual Heritage

------------------------------------------------------------------------

<span id="page_i1">p. i1</span>

# ====== INDEX.

<div align="center">

|                                                                                                                                                                         |                                                                                                                                                                                                                                  |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| STonehenge *the latest of the* Druid *temples,*                                                                                                                         | Page [1](str03.htm#page_1), [17](str05.htm#page_17), [66](str14.htm#page_66.md)                                                                                                                                                     |
| *Older than the time of the* Saxons *and* Danes*,*                                                                                                                      | [1](str03.htm#page_1), [2](str03.htm#page_2), [3](str03.htm#page_3), [7](str03.htm#page_7), [47](str13.htm#page_47.md)                                                                                                              |
| *Older than the time of the* Roman Britons*,*                                                                                                                           | [1](str03.htm#page_1), [2](str03.htm#page_2), [32](str08.htm#page_32.md)                                                                                                                                                            |
| *Older than the time of the* Belgæ*, who preceded the* Roman *invasion,*                                                                                                | [4](str03.htm#page_4), [8](str04.htm#page_8), [9](str04.htm#page_9), [47](str13.htm#page_47.md)                                                                                                                                     |
| *The history of the* Belgæ *seated about* Stonehenge*, in* Cæsar*'s time,*                                                                                              | [4](str03.htm#page_4), [8](str04.htm#page_8), [47](str13.htm#page_47.md)                                                                                                                                                            |
| *Our* Welsh *the remains of the* Belgæ*,*                                                                                                                               | [8](str04.htm#page_8.md)                                                                                                                                                                                                            |
| *The* Cimbrians *the same,*                                                                                                                                             | [48](str13.htm#page_48.md)                                                                                                                                                                                                          |
| *Of the* Wansdike: *made by* Divitiacus*,*                                                                                                                              | [4](str03.htm#page_4), [47](str13.htm#page_47.md)                                                                                                                                                                                   |
| *Of* Vespasian's *camp* Ambresbury*,*                                                                                                                                   | [49](str13.htm#page_49.md)                                                                                                                                                                                                          |
| *The stones of* Stonehenge *are from the gray weathers on* Marlborough *downs,*                                                                                         | [5](str03.htm#page_5), [47](str13.htm#page_47.md)                                                                                                                                                                                   |
| *Of their nature, magnitude, weight,*                                                                                                                                   | [5](str03.htm#page_5), [6](str03.htm#page_6.md)                                                                                                                                                                                     |
| *Of their number,*                                                                                                                                                      | [30](str08.htm#page_30.md)                                                                                                                                                                                                          |
| * *                                                                                                                                                                     |                                                                                                                                                                                                                                  |
| *Mr.* Webb*'s drawings of* Stonehenge *false,*                                                                                                                          | [3](str03.htm#page_3), [22](str06.htm#page_22), [25](str07.htm#page_25.md)                                                                                                                                                          |
| *Absurd to compare the work to* Roman *or* Grecian *orders,*                                                                                                            | [6](str03.htm#page_6), [10](str04.htm#page_10), [16](str05.htm#page_16), [20](str06.htm#page_20), [21](str06.htm#page_21), [28](str07.htm#page_28.md)                                                                               |
| *The cell not form’d from three equilateral triangles,*                                                                                                                 | [3](str03.htm#page_3), [18](str05.htm#page_18), [24](str07.htm#page_24), [33](str09.htm#page_33.md)                                                                                                                                 |
| *But one entrance into the area,*                                                                                                                                       | [3](str03.htm#page_3), [18](str05.htm#page_18), [23](str06.htm#page_23), [33](str09.htm#page_33.md)                                                                                                                                 |
| *He makes one side of the cell out of a bit of a loose stone,*                                                                                                          | [29](str07.htm#page_29.md)                                                                                                                                                                                                          |
| *He has turn’d the cell a sixth part from its true situation,*                                                                                                          | [3](str03.htm#page_3), [22](str06.htm#page_22.md)                                                                                                                                                                                   |
| *The cell not a hexagon, but an oval,*                                                                                                                                  | [20](str06.htm#page_20), [22](str06.htm#page_22), [29](str07.htm#page_29.md)                                                                                                                                                        |
| *Demonstrated by Lord* Pembroke*'s measure,*                                                                                                                            | [28](str07.htm#page_28.md)                                                                                                                                                                                                          |
| *Demonstrated by trigonometry,*                                                                                                                                         | [22](str06.htm#page_22.md)                                                                                                                                                                                                          |
| *Proved by the surgeons amphitheater,* London*, being an imitation thereof*                                                                                             | [25](str07.htm#page_25.md)                                                                                                                                                                                                          |
| Stonehenge *not made by the* Roman *foot,*                                                                                                                              | [6](str03.htm#page_6.md)                                                                                                                                                                                                            |
| Webb *makes the inner circle, of thirty stones, instead of forty,*                                                                                                      | [20](str06.htm#page_20.md)                                                                                                                                                                                                          |
| *He contracts 119 feet to 43,*                                                                                                                                          | [33](str09.htm#page_33.md)                                                                                                                                                                                                          |
| *He draws a stone on the* vallum 120 *foot out of its true place,*                                                                                                      | [14](str04.htm#page_14.md)                                                                                                                                                                                                          |
| Stonehenge *not a monument,*                                                                                                                                            | [40](str10.htm#page_40.md)                                                                                                                                                                                                          |
| * *                                                                                                                                                                     |                                                                                                                                                                                                                                  |
| *The Druids came with an oriental colony, upon the first* Celtic *inhabitants,*                                                                                         | [62](str14.htm#page_62), [63](str14.htm#page_63.md)                                                                                                                                                                                 |
| *Introduc’d here by the* Tyrian Hercules*,*                                                                                                                             | [7](str03.htm#page_7), [31](str08.htm#page_31), [32](str08.htm#page_32), [50](str13.htm#page_50), [52](str13.htm#page_52), [55](str13.htm#page_55), [63](str14.htm#page_63.md)                                                      |
| *The colony were* Phœnicians *or* Arabians*,*                                                                                                                           | [63](str14.htm#page_63), [66](str14.htm#page_66.md)                                                                                                                                                                                 |
| *They found out our tin mines,*                                                                                                                                         | [32](str08.htm#page_32), [55](str13.htm#page_55), [63](str14.htm#page_63.md)                                                                                                                                                        |
| *The Druids came bitter about* Abraham*'s time or soon after,*                                                                                                          | [2](str03.htm#page_2), [7](str03.htm#page_7), [31](str08.htm#page_31), [32](str08.htm#page_32), [49](str13.htm#page_49), [52](str13.htm#page_52.md)                                                                                 |
| <span id="page_i2">p. i2</span>                                                                                                                                         |                                                                                                                                                                                                                                  |
| *They were of the patriarchal religion,*                                                                                                                                | Page [1](str03.htm#page_1), [2](str03.htm#page_2), [17](str05.htm#page_17.md)                                                                                                                                                       |
| *Which was the same as christianity,*                                                                                                                                   | [2](str03.htm#page_2), [54](str13.htm#page_54.md)                                                                                                                                                                                   |
| *Stonehenge prov’d the work of the Druids from the infinite number of the like, all over the* Britannic *isles,*                                                        | [3](str03.htm#page_3), [8](str04.htm#page_8.md)                                                                                                                                                                                     |
| *Farther suggestions: because accounted sacred, made by magic, medicinal, came from* Ireland*,* Spain*,* Afric*,* Egypt*. In some places the name of Druids remaining,* | [3](str03.htm#page_3), [5](str03.htm#page_5), [9](str04.htm#page_9), [47](str13.htm#page_47), [48](str13.htm#page_48.md)                                                                                                            |
| *From the antiquities dug up about them,*                                                                                                                               | [4](str03.htm#page_4), [45](str12.htm#page_45), [46](str12.htm#page_46.md)                                                                                                                                                          |
| Schetland *isles the* Hyperboreans *of the* Greeks*, thence* Abaris *the* Pythagorean *philosopher,*                                                                    | [40](str10.htm#page_40.md)                                                                                                                                                                                                          |
| Stonehenge *not built by the* Saxons*, deduced from its name,*                                                                                                          | [7](str03.htm#page_7), [47](str13.htm#page_47.md)                                                                                                                                                                                   |
| *Demonstrated to be older than* Roman *times,*                                                                                                                          | [9](str04.htm#page_9), [10](str04.htm#page_10.md)                                                                                                                                                                                   |
| *Such in countries never conquered by the* Romans*,*                                                                                                                    | [3](str03.htm#page_3.md)                                                                                                                                                                                                            |
| Stonehenge *and such works built by the* Phœnician *colony,*                                                                                                            | [8](str04.htm#page_8), [9](str04.htm#page_9), [32](str08.htm#page_32), [49](str13.htm#page_49.md)                                                                                                                                   |
| *The cathedral of the Arch-Druid,*                                                                                                                                      | [8](str04.htm#page_8), [10](str04.htm#page_10), [32](str08.htm#page_32.md)                                                                                                                                                          |
| *Called antiently the* Ambres*,*                                                                                                                                        | [9](str04.htm#page_9), [47](str13.htm#page_47.md)                                                                                                                                                                                   |
| *Thence* Vespasian*'s camp, and* Ambresbury *nam’d,*                                                                                                                    | [49](str13.htm#page_49.md)                                                                                                                                                                                                          |
| Stonehenge *call’d* choir gaur: *the great church or cathedral,*                                                                                                        | [4](str03.htm#page_4), [47](str13.htm#page_47.md)                                                                                                                                                                                   |
| *Made with mortaise and tenon, unusual with the* Romans*,*                                                                                                              | [18](str05.htm#page_18.md)                                                                                                                                                                                                          |
| *Made by the ancient* Hebrew*,* Phœnician *cubit,*                                                                                                                      | [6](str03.htm#page_6), [12](str04.htm#page_12), [28](str07.htm#page_28.md)                                                                                                                                                          |
| *Its proportion to our foot,*                                                                                                                                           | [6](str03.htm#page_6), [11](str04.htm#page_11), [15](str05.htm#page_15), [26](str07.htm#page_26), [30](str08.htm#page_30), [32](str08.htm#page_32.md)                                                                               |
| *The ancient* decem-pedum*,*                                                                                                                                            | [12](str04.htm#page_12.md)                                                                                                                                                                                                          |
| *The Druids were geometricians,*                                                                                                                                        | [16](str05.htm#page_16), [18](str05.htm#page_18), [27](str07.htm#page_27), [42](str11.htm#page_42.md)                                                                                                                               |
| *Knew the use of the compass,*                                                                                                                                          | [57](str14.htm#page_57), [63](str14.htm#page_63.md)                                                                                                                                                                                 |
| *They carried a little ax to cut down misletoe,*                                                                                                                        | [39](str10.htm#page_39), [48](str13.htm#page_48.md)                                                                                                                                                                                 |
| *The Druids letter,*                                                                                                                                                    | [31](str08.htm#page_31), [54](str13.htm#page_54.md)                                                                                                                                                                                 |
| * *                                                                                                                                                                     |                                                                                                                                                                                                                                  |
| *The patriarchal temples were open,*                                                                                                                                    | [19](str05.htm#page_19), [23](str06.htm#page_23), [30](str08.htm#page_30), [39](str10.htm#page_39), [40](str10.htm#page_40), [46](str12.htm#page_46), [52](str13.htm#page_52), [54](str13.htm#page_54), [58](str14.htm#page_58.md). |
| Moses*'s tabernacle the first cover’d temple,*                                                                                                                          | [23](str06.htm#page_23), [24](str07.htm#page_24), [58](str14.htm#page_58.md)                                                                                                                                                        |
| *Patriarchal temples,*                                                                                                                                                  | [19](str05.htm#page_19), [40](str10.htm#page_40), [46](str12.htm#page_46), [50](str13.htm#page_50), [51](str13.htm#page_51), [54](str13.htm#page_54.md)                                                                             |
| *Of rude stones, unchizel’d,*                                                                                                                                           | [66](str14.htm#page_66.md)                                                                                                                                                                                                          |
| *The* kebla*,*                                                                                                                                                          | [24](str07.htm#page_24), [30](str08.htm#page_30), [40](str10.htm#page_40), [54](str13.htm#page_54.md)                                                                                                                               |
| *Had no statues,*                                                                                                                                                       | [55](str13.htm#page_55.md)                                                                                                                                                                                                          |
| *Patriarchal altars,*                                                                                                                                                   | [30](str08.htm#page_30), [50](str13.htm#page_50), [52](str13.htm#page_52.md)                                                                                                                                                        |
| *Their temples fronted the east,*                                                                                                                                       | [35](str10.htm#page_35.md)                                                                                                                                                                                                          |
| *Their temples were consecrated and endowed,*                                                                                                                           | [52](str13.htm#page_52.md)                                                                                                                                                                                                          |
| *Paying tythe,*                                                                                                                                                         | [52](str13.htm#page_52), [55](str13.htm#page_55.md)                                                                                                                                                                                 |
| *Bowing, a part of worship,*                                                                                                                                            | [33](str09.htm#page_33), [34](str09.htm#page_34.md)                                                                                                                                                                                 |
| *They officiated  barefooted,*                                                                                                                                          | [55](str13.htm#page_55.md)                                                                                                                                                                                                          |
| *They practised chastity, before officiating,*                                                                                                                          | ibid.                                                                                                                                                                                                                            |
| *The priests wore white linen surplices at the time of officiating,*                                                                                                    | [24](str07.htm#page_24), [55](str13.htm#page_55.md)                                                                                                                                                                                 |
| *Their publick demotion was call’d praying, or invoking, in the NAME,*                                                                                                  | [52](str13.htm#page_52.md)                                                                                                                                                                                                          |
| *They believ’d a future state,*                                                                                                                                         | [31](str08.htm#page_31.md)                                                                                                                                                                                                          |
| *They gave notice of religious festivals by fire,*                                                                                                                      | [37](str10.htm#page_37.md)                                                                                                                                                                                                          |
| *Those were the quarterly sacrifices,*                                                                                                                                  | ibid.                                                                                                                                                                                                                            |
| *The manner of sacrificing,*                                                                                                                                            | [34](str09.htm#page_34), [54](str13.htm#page_54.md)                                                                                                                                                                                 |
| *They us’d water for purification,*                                                                                                                                     | [11](str04.htm#page_11), [13](str04.htm#page_13), [14](str04.htm#page_14), [34](str09.htm#page_34.md)                                                                                                                               |
| * *                                                                                                                                                                     |                                                                                                                                                                                                                                  |
| *Of the water vases at* Stonehenge*,*                                                                                                                                   | [11](str04.htm#page_11), [13](str04.htm#page_13), [14](str04.htm#page_14), [34](str09.htm#page_34.md)                                                                                                                               |
| *The stone table there,*                                                                                                                                                | [34](str09.htm#page_34.md)                                                                                                                                                                                                          |
| *Of the stones and cavities on the* vallum*,*                                                                                                                           | [11](str04.htm#page_11), [14](str04.htm#page_14.md)                                                                                                                                                                                 |
| Crwm-lechen*, bowing stones,*                                                                                                                                           | [33](str09.htm#page_33), [34](str09.htm#page_34.md)                                                                                                                                                                                 |
| * *                                                                                                                                                                     |                                                                                                                                                                                                                                  |
| *<span id="page_i3">p. i3</span>*                                                                                                                                       |                                                                                                                                                                                                                                  |
| *Human sacrifices,*                                                                                                                                                     | Page [54](str13.htm#page_54.md)                                                                                                                                                                                                     |
| *Heathen imitations of the* Jews*,*                                                                                                                                     | [46](str12.htm#page_46), [60](str14.htm#page_60), [62](str14.htm#page_62.md)                                                                                                                                                        |
| Main Ambres*, rocking stones,* gygonia*,* petræ ambrosiæ*,* Bæthylia*,*                                                                                                 | [18](str05.htm#page_18), [49](str13.htm#page_49), [50](str13.htm#page_50), [51](str13.htm#page_51), [52](str13.htm#page_52), [54](str13.htm#page_54.md)                                                                             |
| Ambrosia *what?*                                                                                                                                                        | [51](str13.htm#page_51), [52](str13.htm#page_52.md).                                                                                                                                                                                |
| *Horned, anointed, analogous to sacred, consecrated,*                                                                                                                   | [52](str13.htm#page_52), [59](str14.htm#page_59.md)                                                                                                                                                                                 |
| * *                                                                                                                                                                     |                                                                                                                                                                                                                                  |
| *The time when* Hercules *lived,*                                                                                                                                       | [52](str13.htm#page_52), [53](str13.htm#page_53), [58](str14.htm#page_58.md)                                                                                                                                                        |
| Hercules *built patriarchal temples, where-ever he came,*                                                                                                               | [54](str13.htm#page_54), [57](str14.htm#page_57.md)                                                                                                                                                                                 |
| *Probably he made the* Main Ambre *by* Pensans*, and* Biscawoon*,*                                                                                                      | [54](str13.htm#page_54.md)                                                                                                                                                                                                          |
| Persepolis *a patriarchal temple,*                                                                                                                                      | [19](str05.htm#page_19), [45](str12.htm#page_45.md)                                                                                                                                                                                 |
| *Of the avenue of* Stonehenge*,*                                                                                                                                        | [35](str10.htm#page_35), [39](str10.htm#page_39.md)                                                                                                                                                                                 |
| *Of its two wings,*                                                                                                                                                     | [35](str10.htm#page_35), [38](str10.htm#page_38), [41](str11.htm#page_41), [57](str14.htm#page_57.md)                                                                                                                               |
| *Eastern wing, its variation,*                                                                                                                                          | [36](str10.htm#page_36), [56](str14.htm#page_56), [57](str14.htm#page_57), [64](str14.htm#page_64), [57](str14.htm#page_57.md)                                                                                                      |
| *Of the* Hippodrom *or* Cursus*,*                                                                                                                                       | [13](str04.htm#page_13), [41](str11.htm#page_41), [56](str14.htm#page_56.md)                                                                                                                                                        |
| *Its variation,*                                                                                                                                                        | [42](str11.htm#page_42), [57](str14.htm#page_57.md)                                                                                                                                                                                 |
| *The* Romans *borrowed the* British *chariots,*                                                                                                                         | [42](str11.htm#page_42.md)                                                                                                                                                                                                          |
| *The eastern* meta*, its variation,*                                                                                                                                    | [57](str14.htm#page_57.md)                                                                                                                                                                                                          |
| *Other like works, in other parts of* England*,*                                                                                                                        | [43](str11.htm#page_43.md)                                                                                                                                                                                                          |
| *The* via Iceniana*,*                                                                                                                                                   | [9](str04.htm#page_9.md)                                                                                                                                                                                                            |
| * *                                                                                                                                                                     |                                                                                                                                                                                                                                  |
| *Of the barrows or sepulchral* tumuli*,*                                                                                                                                | [43](str11.htm#page_43.md)                                                                                                                                                                                                          |
| *Druid barrows,*                                                                                                                                                        | [10](str04.htm#page_10), [45](str12.htm#page_45.md)                                                                                                                                                                                 |
| *Arch-Druids barrows,*                                                                                                                                                  | [38](str10.htm#page_38.md)                                                                                                                                                                                                          |
| *Urn burial,*                                                                                                                                                           | [44](str12.htm#page_44), [46](str12.htm#page_46.md)                                                                                                                                                                                 |
| *The bodies lay north and south,*                                                                                                                                       | [45](str12.htm#page_45.md)                                                                                                                                                                                                          |
| *Beads of amber, glass, gold,* &c. *found,*                                                                                                                             | ibid.                                                                                                                                                                                                                            |
| *Horses, dogs, and other animals buried with them,*                                                                                                                     | [46](str12.htm#page_46.md)                                                                                                                                                                                                          |
| Carvilius*'s tomb,*                                                                                                                                                     | [4](str03.htm#page_4), [44](str12.htm#page_44), [46](str12.htm#page_46.md)                                                                                                                                                          |
| * *                                                                                                                                                                     |                                                                                                                                                                                                                                  |
| *The magnetical compass known to* Hercules*, the* Phœnicians *and* Arabians*,*                                                                                          | [57](str14.htm#page_57.md)                                                                                                                                                                                                          |
| *The oracle of* Jupiter Ammon *had a compass,*                                                                                                                          | [59](str14.htm#page_59), [61](str14.htm#page_61), [62](str14.htm#page_62.md)                                                                                                                                                        |
| *The golden fleece was a compass,*                                                                                                                                      | [60](str14.htm#page_60), [62](str14.htm#page_62.md)                                                                                                                                                                                 |
| *How the compass was forgot,*                                                                                                                                           | [55](str13.htm#page_55), [58](str14.htm#page_58), [63](str14.htm#page_63), [64](str14.htm#page_64.md)                                                                                                                               |
| *Apher grandson of* Abraham*, companion of* Hercules*, from* Arabia*,*                                                                                                  | [53](str13.htm#page_53), [62](str14.htm#page_62), [63](str14.htm#page_63.md)                                                                                                                                                        |
| *He gave name to* Africa *and to* Britain*,*                                                                                                                            | [53](str13.htm#page_53), [62](str14.htm#page_62), [63](str14.htm#page_63.md)                                                                                                                                                        |
| *A scheme of the variation of the compass,*                                                                                                                             | [65](str14.htm#page_65.md)                                                                                                                                                                                                          |
| *A conjecture therefrom, when* Stonehenge *was founded,*                                                                                                                | [65](str14.htm#page_65.md)                                                                                                                                                                                                          |

</div>

 

 

*F I N I S*.

 

 

 
