[![](../../cdshop/ithlogo.png)](../../index.md)  
[Intangible Textual Heritage](../../index)  [Islam](../index.md)  [Shiite
Texts](../shi.md) 

------------------------------------------------------------------------

<table width="75%">
<colgroup>
<col style="width: 100%" />
</colgroup>
<tbody>
<tr class="odd">
<td width="50%" data-valign="TOP"><h1 id="the-alawite-book" data-align="CENTER">The Alawite Book</h1></td>
</tr>
</tbody>
</table>

------------------------------------------------------------------------

------------------------------------------------------------------------

[A Word](sal000.md)  
[Introduction](sal001.md)  
[Dua Yastasheer (pray of Yastasheer)](sal002.md)  
[His Prayer for Eulogizing Allah and Expressing His greatness](sal003.md)  
[His Prayer in Praise and Eulogy of Allah for all important affairs and
problems](sal004.md)  
[Dua-e-Owais-e-Qarni](sal005.md)  
[His prayers praising Allah as taught to
Janab-e-Owais-e-Qarni](sal006.md)  
[His prayers mentioning the names of Allah](sal007.md)  
[Dua-e-Mashlool](sal008.md)  
[His Supplication mentioning Isme Azam](sal009.md)  
[His Supplication in Praise of Allah](sal010.md)  
[Dua-e-Jaameah](sal011.md)  
[Dua-e-Mazkoor](sal012.md)  
[His Dua mentioning the Holy Prophet](sal013.md)  
[His supplication, invoking peace on Prophet](sal014.md)  
[His Dua expressing helplessness before the Almighty](sal015.md)  
[His Dua for expressing helplessness before Allah and seeking
forgiveness](sal016.md)  
[His Dua expressing sincere attention towards Allah](sal017.md)  
[Dua recited in morning prayers at the time of Dawn](sal018.md)  
[Dua seeking Pardon](sal019.md)  
[His Dua seeking forgiveness](sal020.md)  
[Dua seeking forgiveness](sal021.md)  
[Dua for seeking forgiveness](sal022.md)  
[Dua seeking forgiveness](sal023.md)  
[His Supplication expressing devotion to Allah](sal024.md)  
[An elegy (Munajat)](sal025.md)  
[Another Elegy of Imam Ali (a.s.)](sal026.md)  
[His Dua at the time of severe difficulties](sal027.md)  
[His supplication for the honoured month of Shaban](sal028.md)  
[Dua-e-Kumail](sal029.md)  
[His supplication on sighting the New Moon](sal030.md)  
[Another of his supplication on sighting the Moon](sal031.md)  
[His supplication on sighting the moon of the month of Ramazan recited
facing the Qibla](sal032.md)  
[His supplication at the time of breaking the fast](sal033.md)  
[Supplication the Holy Prophet (s.a.w.a.) taught him and he recited it
at the time of ending the fast](sal034.md)  
[His supplication while prostrating](sal035.md)  
[His supplication in the first 10 days of Zilhajj](sal036.md)  
[His supplication when he was ill](sal037.md)  
[His supplication for being cured from disease](sal038.md)  
[His supplication for every physical pain](sal039.md)  
[His supplication for cure from dropsy](sal040.md)  
[His supplication for fits](sal041.md)  
[His supplication for toothache](sal042.md)  
[His supplication for stomachache to be recited after drinking some hot
water](sal043.md)  
[His supplication for piles](sal044.md)  
[His supplication at the time of childbirth](sal045.md)  
[His supplication for fever as taught by the Holy Prophet
(s.a.w.a.)](sal046.md)  
[His supplication to save from drowning or burning](sal047.md)  
[His supplication for those having moles](sal048.md)  
[His supplication to be written on the deer's skin to avert black
magic](sal049.md)  
[His supplication like a fort](sal050.md)  
[His supplication for warding off calamities and seeking
protection](sal051.md)  
[His supplication when sustenance becomes scarce](sal052.md)  
[His supplication seeking refuge from Allah](sal053.md)  
[His supplication in asking for needs and attaining Proximity to
Allah](sal054.md)  
[Dua-e-Yamani](sal055.md)  
[Another of his supplication in troubles](sal056.md)  
[His supplication seeking protection from the enemies](sal057.md)  
[His supplication for seeking sustenance](sal058.md)  
[His supplication for seeking sustenance](sal059.md)  
[His supplication, which he used to recite three times in the
morning](sal060.md)  
[Another of his supplications to be recited in the morning](sal061.md)  
[His supplication, which he recited every morning and evening](sal062.md)  
[Dua-e-Sabah](sal063.md)  
[His supplication for repayment of debts](sal064.md)  
[His supplication for paying of debts](sal065.md)  
[His supplication for seeking desires](sal066.md)  
[His supplication, which is curse for the enemies](sal067.md)  
[His supplication cursing the enemies](sal068.md)  
[His supplication for averting the trap of the enemies](sal069.md)  
[His supplication for safety from calamities](sal070.md)  
[His supplication for victory over the enemies](sal071.md)  
[His supplication when people gathered around him](sal072.md)  
[Supplication of grief](sal073.md)  
[His supplication in the Battlefield of Siffin](sal074.md)  
[His supplication before the Battle of Jamal](sal075.md)  
[His supplication when he used to fight the enemy](sal076.md)  
[His supplication when he was aggrieved](sal077.md)  
[His supplication for achieving martyrdom in the way of Allah](sal078.md)  
[His supplication for reforming his enemies](sal079.md)  
[His supplication when he extorted people for the war of
Siffin](sal080.md)  
[His supplication for the return of the one who flees the
battlefield](sal081.md)  
[Another of His supplication for the return of the one who
flees](sal082.md)  
[His supplication to be recited after praying...](sal083.md)  
[His supplication when someone praised him in his presence](sal084.md)  
[His supplication seeking refuge from show-off](sal085.md)  
[His supplication seeking the opinion of Allah](sal086.md)  
[His supplication when leaving for a journey](sal087.md)  
[His supplication while going to Yemen](sal088.md)  
[His supplication while riding his horse to battlefield](sal089.md)  
[His supplication for rains known as 'Istiskaa'](sal090.md)  
[His supplication after four units of prayer](sal091.md)  
[His supplication while pouring wuzu water](sal092.md)  
[His supplication while urinating](sal093.md)  
[His supplication while rinsing the mouth](sal094.md)  
[His supplication while rinsing the nostrils](sal095.md)  
[His supplication while washing the face](sal096.md)  
[His supplication while washing his right hand](sal097.md)  
[His supplication while washing his left hand](sal098.md)  
[His supplication while wiping his head](sal099.md)  
[His supplication while wiping his feet](sal100.md)  
[His supplication for Nafilah on Friday](sal101.md)  
[His supplication recited after entering the mosque](sal102.md)  
[His supplication after the five daily prayers](sal103.md)  
[His supplication after every obligatory prayer](sal104.md)  
[Another of His supplication after the morning prayers](sal105.md)  
[His supplication after every prayer for protection and
safety](sal106.md)  
[His supplication for memorizing the Quran](sal107.md)  
[His supplication in the middle of the night](sal108.md)  
[His supplication after completing eight rakats](sal109.md)  
[His supplication recited standing in Watr prayer](sal110.md)  
[His supplication on the eve of Saturday](sal111.md)  
[His supplication at the time of mid-day](sal112.md)  
[His supplication when prostrating for thanking Allah](sal113.md)  
[His supplication in prostration of thankfulness](sal114.md)  
[His supplication recited in prostration](sal115.md)  
[His supplication at the times of going to bed](sal116.md)  
[His supplication when turning sideways on bed](sal117.md)  
[His supplication after waking](sal118.md)  
[His Supplication as taught to Imam Hasan (a.s.)](sal119.md)  
[His Supplication as taught to Imam Husain (a.s.)](sal120.md)  
[His supplication known as “Saname Quraish” (Cursing the Idol of
Quraish)](sal121.md)  
[His Supplication known as “KalimaatilFaraj”](sal122.md)  
[His supplication for increasing faith](sal123.md)  
[His Supplication after completing the Holy Quran](sal124.md)  
[His supplication for the first day of the month](sal125.md)  
[His supplication for the second day of the month](sal126.md)  
[His supplication for the third of the month](sal127.md)  
[His supplication for the fourth of the month](sal128.md)  
[His supplication for the fifth of the month](sal129.md)  
[His supplication for the sixth of the month](sal130.md)  
[His supplication for the seventh of the month](sal131.md)  
[His supplication for the eighth of the month](sal132.md)  
[His supplication for the ninth of the month](sal133.md)  
[His supplication for the tenth of the month](sal134.md)  
[His supplication for the eleventh of the month](sal135.md)  
[His supplication for the twelfth of the month](sal136.md)  
[His supplication for the thirteenth of the month](sal137.md)  
[His supplication for the fourteenth of the month](sal138.md)  
[His supplication for the fifteenth of the month](sal139.md)  
[His supplication for the sixteenth of the month](sal140.md)  
[His supplication for the seventeenth of the month](sal141.md)  
[His supplication for the eighteenth of the month](sal142.md)  
[His supplication for the nineteenth of the month](sal143.md)  
[His supplication for the twentieth of the month](sal144.md)  
[His supplication for the twenty-first of the month](sal145.md)  
[His supplication for the twenty-second of the month](sal146.md)  
[His supplication for the twenty-third of the month](sal147.md)  
[His supplication for the twenty-fourth of the month](sal148.md)  
[His supplication for the twenty-fifth of the month](sal149.md)  
[His supplication for the twenty-sixth of the month](sal150.md)  
[His supplication for the twenty-seventh of the month](sal151.md)  
[His supplication for the twenty-eighth of the month](sal152.md)  
[His supplication for the twenty-ninth of the month](sal153.md)  
[His supplication for the thirtieth of the month](sal154.md)  
[His supplication for Friday](sal155.md)  
[His supplication for Saturday](sal156.md)  
[His supplication for Sunday](sal157.md)  
[His Supplication for Monday](sal158.md)  
[His Supplication for Tuesday](sal159.md)  
[His Supplication for Wednesday](sal160.md)  
[His Supplication for Thursday](sal161.md)  
[Another of his Supplication (Munajat)](sal162.md)  
