<div class="filenav">

[![](../../cdshop/ithlogo.png)](../../index.md)  
[Intangible Textual Heritage](../../index)  [Islam](../index.md)   
[Hypertext Quran](../htq/index)  [Unicode Quran](../uq/index.md) 
[Pickthall](../pick/index)  [Palmer Part I (SBE06)](../sbe06/index.md) 
[Palmer Part II (SBE09)](../sbe09/index.md)  [Yusuf
Ali/Arabic](../quran/index)  [Yusuf Ali English](../yaq/index.md)   

</div>

------------------------------------------------------------------------

# The Koran

### Translated by J.M. Rodwell

#### \[1876\]

------------------------------------------------------------------------

[Contents](#contents)    [Start Reading](qrtp.md)    [Text
\[Zipped\]](qr.txt.gz.md)

------------------------------------------------------------------------

<span id="contents"></span> [Title Page](qrtp.md)  
[Introduction](qrintro.md)  
[Dedication](qrded.md)  
[Preface](qrpref.md)  
[Sura XCVI.--Thick Blood, or Clots Of Blood \[I.\]](096.md)  
[Sura LXXIV.--The Enwrapped \[II.\]](074.md)  
[Sura LXXIII. The Enfolded \[III.\]](073.md)  
[Sura XCIII.--The Brightness \[IV.\]](093.md)  
[Sura XCIV.--The Opening \[V.\]](094.md)  
[Sura CXIII.--The Daybreak \[VI.\]](113.md)  
[Sura CXIV.--Men \[VII.\]](114.md)  
[Sura I. \[VIII.\]](001.md)  
[Sura CIX.--Unbelievers \[IX.\]](109.md)  
[Sura CXII.--The Unity \[X.\]](112.md)  
[Sura CXI. Abu Lahab \[XI.\]](111.md)  
[Sura CVIII.--The Abundance \[XII.\]](108.md)  
[Sura CIV.--The Backbiter \[XII.\]](104.md)  
[Sura CVII.--Religion \[XIV.\]](107.md)  
[Sura CII.--Desire \[XV.\]](102.md)  
[Sura XCII.--The Night \[XVI.\]](092.md)  
[Sura LXVIII.--The Pen \[XVII.\]](068.md)  
[Sura XC.--The Soil \[XVIII.\]](090.md)  
[Sura CV.--The Elephant \[XIX.\]](105.md)  
[Sura CVI.--The Koreisch \[XX.\]](106.md)  
[Sura XCVII.--Power \[XXI.\]](097.md)  
[Sura LXXXVI. The Night-Comer \[XXII.\]](086.md)  
[Sura XCI.--The Sun \[XXIII.\]](091.md)  
[Sura LXXX.--He Frowned \[XXIV.\]](080.md)  
[Sura LXXXVII.--The Most High \[XXV.\]](087.md)  
[Sura XCV.--The Fig \[XXVI.\]](095.md)  
[Sura CIII.--The Afternoon \[XXVII.\]](103.md)  
[Sura LXXXV.--The Starry \[XXVIII.\]](085.md)  
[Sura CI.--The Blow \[XXIX.\]](101.md)  
[Sura XCIX.--The Earthquake \[XXX.\]](099.md)  
[Sura LXXXII.--The Cleaving \[XXXI.\]](082.md)  
[Sura LXXXI.--The Folded Up \[XXXII.\]](081.md)  
[Sura LXXXIV.--The Splitting Asunder \[XXXIII.\]](084.md)  
[Sura C.--The Chargers \[XXXIV.\]](100.md)  
[Sura LXXIX.--Those Who Drag Forth \[XXXV.\]](079.md)  
[Sura LXXVII.--The Sent \[XXXVI.\]](077.md)  
[Sura LXXVIII.--The News \[XXXVII.\]](078.md)  
[Sura LXXXVIII.--The Overshadowing \[XXXVIII.\]](088.md)  
[Sura LXXXIX.--The Daybreak \[XXXIX.\]](089.md)  
[Sura LXXV.--The Resurrection \[XL.\]](075.md)  
[Sura LXXXIII.--Those Who Stint \[XLI.\]](083.md)  
[Sura LXIX.--The Inevitable \[XLII.\]](069.md)  
[Sura LI.--The Scattering \[XLIII.\]](051.md)  
[Sura LII.--The Mountain \[XLIV.\]](052.md)  
[Sura LVI.--The Inevitable \[XLV.\]](056.md)  
[Sura LIII.--The Star \[XLVI.\]](053.md)  
[Sura LXX.--The Steps or Ascents \[XLVII.\]](070.md)  
[Sura LV.--The Merciful \[XLVIII.\]](055.md)  
[Sura LIV.--The Moon \[XLIX.\]](054.md)  
[Sura XXXVII.--The Ranks \[L.\]](037.md)  
[Sura LXXI.--Noah \[LI.\]](071.md)  
[Sura LXXVI.--Man \[LII.\]](076.md)  
[Sura XLIV.--Smoke \[LIII.\]](044.md)  
[Sura L.--Kaf \[LIV.\]](050.md)  
[Sura XX.--Ta. Ha. \[LV.\]](020.md)  
[Sura XXVI.--The Poets \[LVI.\]](026.md)  
[Sura XV.--Hedjr \[LVII.\]](015.md)  
[Sura XIX.--Mary \[LVIII.\]](019.md)  
[Sura XXXVIII.--Sad \[LIX.\]](038.md)  
[Sura XXXVI.--Ya. Sin \[LX.\]](036.md)  
[Sura XLIII.--Ornaments of Gold \[LXI.\]](043.md)  
[Sura LXXII.--Djinn \[LXII.\]](072.md)  
[Sura LXVII.--The Kingdom \[LXIII.\]](067.md)  
[Sura XXIII.--The Believers \[LXIV.\]](023.md)  
[Sura XXI.--The Prophets \[LXV.\]](021.md)  
[Sura XXV.--Al Furkan \[LXVI.\]](025.md)  
[Sura XVII.--The Night Journey \[LXVII.\]](017.md)  
[Sura XXVII.--The Ant \[LXVIII.\]](027.md)  
[Sura XVIII.--The Cave \[LXIX.\]](018.md)  
[Sura XXXII.--Adoration \[LXX.\]](032.md)  
[Sura XLI.--The Made Plain \[LXXI.\]](041.md)  
[Sura XLV.--The Kneeling \[LXXII.\]](045.md)  
[Sura XVI.--The Bee \[LXXIII.\]](016.md)  
[Sura XXX.--The Greeks \[LXXIV.\]](030.md)  
[Sura XI.--Houd \[LXXV.\]](011.md)  
[Sura XIV.--Abraham, On Whom Be Peace \[LXXVI.\]](014.md)  
[Sura XII.--Joseph, Peace Be On Him \[LXXVII.\]](012.md)  
[Sura XL.--The Believer \[LXXVIII.\]](040.md)  
[Sura XXVIII.--The Story \[LXXIX.\]](028.md)  
[Sura XXXIX.--The Troops \[LXXX.\]](039.md)  
[Sura XXIX.--The Spider \[LXXXI.\]](029.md)  
[Sura XXXI.--Lokman \[LXXXII.\]](031.md)  
[Sura XLII.--Counsel \[LXXXIII.\]](042.md)  
[Sura X.--Jonah, Peace Be On Him! \[LXXXIV.\]](010.md)  
[Sura XXXIV.--Saba \[LXXXV.\]](034.md)  
[Sura XXXV.--The Creator, Or The Angels \[LXXXVI.\]](035.md)  
[Sura VII.--Al Araf \[LXXXVII.\]](007.md)  
[Sura XLVI.--Al Ahkaf \[LXXXVIII.\]](046.md)  
[Sura VI.--Cattle \[LXXXIX.\]](006.md)  
[Sura XIII.--Thunder \[XC.\]](013.md)  
[Sura II.--The Cow \[XCI.\]](002.md)  
[Sura XCVIII.--Clear Evidence \[XCII.\]](098.md)  
[Sura LXIV.--Mutual Deceit \[XCIII.\]](064.md)  
[Sura LXII.--The Assembly \[XCIV.\]](062.md)  
[Sura VIII.--The Spoils \[XCV.\]](008.md)  
[Sura XLVII.--Muhammad \[XCVI.\]](047.md)  
[Sura III.--The Family of Imran \[XCVII.\]](003.md)  
[Sura LXI.--Battle Array \[XCVIII.\]](061.md)  
[Sura LVII.--Iron \[XCIX.\]](057.md)  
[Sura IV.--Women \[C.\]](004.md)  
[Sura LXV.--Divorce \[CI.\]](065.md)  
[Sura LIX.--The Emigration \[CII.\]](059.md)  
[Sura XXXIII.--The Confederates \[CIII.\]](033.md)  
[Sura LXIII.--The Hypocrites \[CIV.\]](063.md)  
[Sura XXIV.--Light \[CV.\]](024.md)  
[Sura LVIII.--She Who Pleaded \[CVI.\]](058.md)  
[Sura XXII.--The Pilgrimage \[CVII.\]](022.md)  
[Sura XLVIII.--The Victory \[CVIII.\]](048.md)  
[Sura LXVI.--The Forbidding \[CIX.\]](066.md)  
[Sura LX.--She Who Is Tried \[CX.\]](060.md)  
[Sura CX.--Help \[CXI.\]](110.md)  
[Sura XLIX.--The Apartments \[CXII.\]](049.md)  
[Sura IX.--Immunity \[CXIII.\]](009.md)  
[Sura V.--The Table \[CXIV.\]](005.md)  
[Index](qridx.md)  
