[![](../../cdshop/ithlogo.png)](../../index.md)  
[Intangible Textual Heritage](../../index)  [Age of Reason](../index.md) 
[Index](index)  [Previous](v1cont)  [Next](v1intro.md) 

------------------------------------------------------------------------

[Buy this Book at
Amazon.com](https://www.amazon.com/exec/obidos/ASIN/0486225720/internetsacredte.md)

------------------------------------------------------------------------

<span id="page_xxv">p. xxv</span>

All drawings here reproduced are in pen and ink, unless otherwise
stated. The reproductions are of the exact size of the originals, except
that Plates I, [XVIII](pl028.htm#img_pl028.md) and are slightly reduced.
Plate I is the frontispiece; Plate II is on [p.
124](pl002.htm#page_124.md); Plates III--XXXV follow [p.
124](pl002.htm#page_124.md); Plate XXXVI is on p. 202; Plates XXXVII--LXIV
follow p. 202.

### LIST OF ILLUSTRATIONS IN VOLUME I.

|                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                             |
|-------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------|
| [Pl. I](v1title.htm#img_pl001.md).     | Portrait of Leonardo, by himself, reproduced from the original drawing in red chalk in the Royal Library, Turin--see No. 1368, Note                                                                                                                                                                                                                                                                                                                                                                                                                                                |                             |
| [Pl. II](pl002.htm#img_pl002.md).      | Three Diagrams, illustrating the theories of Linear Perspective and of Light and Shade: No. 1 from the Ashburnham MS. I No. 1--see text No. 61. Nos. 2 and 3 from MS. C., Institut de France, Paris--see text No. 141                                                                                                                                                                                                                                                                                                                                                              |                             |
| [Pl. III](pl003.htm#img_pl003.md).     | Two Diagrams, illustrating the theory of Light and Shade; from the Ashburnham MS. I: No. 1--see text Nos. 148 and 275--; No. 2--see text No. 149                                                                                                                                                                                                                                                                                                                                                                                                                                   |                             |
| [Pl. IV](p1004.htm#img_pl004.md).      | Five Diagrams, illustrating the theory of Light and Shade: No. 1 from MS. E, Institut de France, Paris--see text No. 162--; Nos. 2 and 3 from the Ashburnham MS. I--see text Nos. 169 and 173--; Nos. 4 and 5 from the Codex Atlanticus, Ambrosian Library, Milan--see text Nos. 179 and 187                                                                                                                                                                                                                                                                                       |                             |
| [Pl. V](pl005.htm#img_pl005.md).       | Diagram, illustrating the theory of Light and Shade and Sketches of Figures illustrating the Movements of the Human Figure; from the Royal Library, Windsor Castle--see text Nos. 183 and 597                                                                                                                                                                                                                                                                                                                                                                                      |                             |
| [Pl. VI](pl006.htm#img_pl006.md).      | Four Diagrams, illustrating the theory of Light and Shade: No. 1 from the Codex Atlanticus, Milan--see text No. 191--; Nos. 2 and 3 from MS. C, Institut de France, Paris--see text Nos. 215 and 216--; No. 4 from the Ashburnham MS. I--see text No. 224                                                                                                                                                                                                                                                                                                                          |                             |
| [Pl. VII](pl007.htm#img_pl007.md).     | Five Drawings, illustrating the theory of the Proportions of the Human Figure, from the Royal Library, Windsor Castle; No. 1--see text No. 310--; No. 2--see text Nos. 310 and 339--; No. 3--see text No. 313--; No. 4--see text Nos. 321 and 327--; No. 5--see No 595                                                                                                                                                                                                                                                                                                             |                             |
| [Pl. VIII](pl008.htm#img_pl008.md).    | Two Drawings, illustrating the theory of the Proportions of the Human Figure; No. 1 from MS. A, Institut de France, Paris--see text No. 312--; No. 2 from the Royal Library, Windsor Castle--see text No. 332                                                                                                                                                                                                                                                                                                                                                                      |                             |
| [Pl. IX](pl009.htm#img_pl009.md).      | Drawing, illustrating the theory of the Proportions of the Human Figure; from the Accademia at Venice--see text No. 315                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                             |
|                                     | <span id="page_xxvi">p. xxvi</span>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                             |
| [Pl. X](pl010.htm#img_pl010.md).       | Drawing in silverpoint on bluish-toned paper, illustrating the theory of Proportions of the Human Figure; from the Royal Library, Windsor Castle--see text No. 316                                                                                                                                                                                                                                                                                                                                                                                                                 |                             |
| [Pl. XI](pl011.htm#img_pl011.md).      | Drawing, illustrating the theory of Proportions of the Human Figure; from the Royal Library, Windsor Castle--see text No. 318                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                             |
| [Pl. XII](pl012.htm#img_pl012.md).     | Drawing, illustrating the theory of Proportions in, the Human Figure; from the Royal Library, Turin--see text No. 319                                                                                                                                                                                                                                                                                                                                                                                                                                                              |                             |
| [Pl. XIII](pl013.htm#img_pl013.md).    | Two Drawings illustrating the theory of the Proportions of the Human Figure; from the Royal Library Windsor Castle--see text No. 328                                                                                                                                                                                                                                                                                                                                                                                                                                               |                             |
| [Pl. XIV](pl014.htm#img_pl014.md).     | Two drawings, illustrating the theory of Proportions of the Human Figure, from the Royal Library, Windsor Castle; No. 1--see text Nos. 326, 330--; No 2.--see text No. 334                                                                                                                                                                                                                                                                                                                                                                                                         |                             |
| [Pl. XV](pl015.htm#img_pl015.md).      | Sketches, illustrating the theory of the Proportions of the Human Figure; from the Royal Library, Windsor Castle--see text Nos. 331 and 345                                                                                                                                                                                                                                                                                                                                                                                                                                        |                             |
| [Pl. XVI](pl016.htm#img_pl016.md).     | Two Drawings, illustrating the theory of the Proportions of the Human Figure; from the Royal Library, Windsor Castle: No. 1, see text No. 335; No. 2, see text Nos. 339 and 342                                                                                                                                                                                                                                                                                                                                                                                                    |                             |
| [Pl. XVII](pl017.htm#img_pl017.md).    | Two drawings, illustrating the theory of Proportions in the Human Figure; No. 1 from MS. A, Institut de France, Paris--see text No. 313 note--; No. 2 from the Royal Library, Windsor Castle,--see text Nos. 348 and 336                                                                                                                                                                                                                                                                                                                                                           |                             |
| [Pl. XVIII](pl018.htm#img_pl018.md).   | Drawing, illustrating the Proportions of the Human Figure, from the Accademia, Venice --see text No. 343                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |                             |
| [Pl. XIX](pl019.htm#img_pl019.md).     | Two Drawings, illustrating the theory of the Proportions of the Human Figure from the Royal Library, Windsor Castle; No. 1--see text No. 347--; No. 2--see text No. 351                                                                                                                                                                                                                                                                                                                                                                                                            |                             |
| [Pl. XX](pl020.htm#img_pl020.md).      | Drawing, illustrating the theory of the Proportions of the Human Figure; from the Royal Library, Windsor Castle--see text No. 349                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                             |
| [Pl. XXI](pl021.htm#img_pl021.md).     | Drawing in red chalk, illustrating the theory of the Movements of the Human Figure--see text No. 356--, and sketch in pen and ink of warriors fighting--see p. 340;--from the Royal Library, Windsor Castle                                                                                                                                                                                                                                                                                                                                                                        |                             |
| [Pl. XXII](pl022.htm#img_pl022.md).    | Four Drawings, illustrating the theory of the Movements of the Human Figure: Nos. 1 and 2 from the Royal Library, Windsor Castle--see text Nos. 357 and 358--; Nos. 3 and 4 from Manuscript A, Institut de France, Paris--see text Nos. 359 and 369                                                                                                                                                                                                                                                                                                                                |                             |
| [Pl. XXIII](pl023.htm#img_pl023.md).   | Four Drawings, illustrating the theory of the Movements of the Human Figure: No. 1 from the Royal Library, Windsor Castle--see text No. 375--; No. 2, in red chalk, from MS. II.<sup>2</sup>, South Kensington Museum, London --see text Nos. 376 and 1395--; No. 3, in red chalk, from Manuscript II.<sup>2</sup>, Institut de France, Paris--see text No. 377--; No. 4 from the Royal Library, Windsor Castle--see text No. 379                                                                                                                                                  |                             |
| [Pl. XXIV](pl024.htm#img_pl024.md).    | Three Drawings, illustrating the theory of the Movements of the Human Figure: No. 1 from the Royal Library, Windsor Castle--see text No. 387--; No. 2 from the Codex Atlanticus, Milan--see text No. 388--; No. 3 from the Leicester Manuscript, Holkham Hall--see text No. 386                                                                                                                                                                                                                                                                                                    |                             |
| [Pl. XXV](pl025.htm#img_pl025.md).     | Drawing, illustrating the representation of the hair falling down in curls; from the Royal Library, Windsor Castle--see text No. 389                                                                                                                                                                                                                                                                                                                                                                                                                                               |                             |
|                                     | <span id="page_xxvii">p. xxvii</span>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |                             |
| [Pl. XXVI](pl026.htm#img_pl026).    | Charcoal Drawing of a Female Figure, from the Royal Library, Windsor Castle--see text No. 391 and [p. 342](0663.htm#page_342.md)                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                             |
| [Pl. XXVII](pl027.htm#img_pl027).   | Five Drawings, illustrating the Botany for Painters; from the Manuscripts M (1) and G (2 to 5.md), Institut de France, Paris: No. 1--see text Nos. 395 and 396--; No. 2--see text Nos. 402 and 412--; No. 3--see text No. 413--; No. 4--see text No. 414--; No. 5--see text No. 417                                                                                                                                                                                                                                                                                                   |                             |
| [Pl. XXVIII](pl028.htm#img_pl028).  | Five Drawings illustrating the Elements of Landscape Painting; from the Manuscripts M, G, E and I<sup>1</sup> in the Institut de France, Paris--No. 1 (MS. M)--see text No. 420--; No. 2 (MS. G)--see text Nos. 424 and 433--; No. 3 (MS. E) see text Nos. 440 and 442--; No. 4 (MS. G)--see text No. 45--; No. 5 (MS. I<sup>1</sup>.md)--see text Nos. 188 and 452--;--and two drawings illustrating the theory of the Arrangement of Folds in Draperies: No. 6 from the Ashburnham Manuscript I--see text No. 390--; No. 7 from the Royal Library, Windsor Castle--see text No. 392 |                             |
| [Pl. XXIX](pl029.htm#img_pl029.md).    | Drawing, in red chalk, representing a Landscape; from the Royal Library, Windsor Castle--see text No. 476                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |                             |
| [Pl. XXX](pl030.htm#img_pl030.md).     | Drawing of a Bust and minor Sketches; from the Royal Library, Windsor Castle--see text Nos. 486 and 487                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                             |
| [Pl. XXXI](pl031.htm#img_pl031.md).    | Four Drawings illustrating the Practice of Painting: No. 1 from the Codex Atlanticus Milan--see text Nos. 490 and 548--; No. 2 from the Ashburnham Manuscript I--see text No. 512;--No. 3 from Manuscript A, Institut de France, Paris--see text No. 526;--No. 4 from the Ashburnham Manuscript I--see text Nos. 573 and 574                                                                                                                                                                                                                                                       |                             |
| [Pl. XXXII](pl032.htm#img_pl032.md).   | Drawing of a male Head, illustrating the Practice of Painting; from the Royal Library, Windsor Castle--see text Nos. 137, 575                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                             |
| [Pl. XXXIII](pl033.htm#img_pl033.md).  | Study of Female Hands, drawn with the silverpoint on yellowish tinted paper, heightened with white; from the Royal Library, Windsor Castle--see text No. 583                                                                                                                                                                                                                                                                                                                                                                                                                       |                             |
|                                     | Drawing of two Men on horseback fighting a Dragon; from the Collection of Baron Edmond de Rothschild, Paris; woodcut page                                                                                                                                                                                                                                                                                                                                                                                                                                                          | [293](0585.htm#page_293.md)    |
|                                     | Drawing of Male Figures in various groups, from the Louvre Collections (reduced in size); woodcut page                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | [297](0594.htm#page_297.md)    |
| [Pl. XXXIV](pl034.htm#img_pl034.md).   | Representation of a Tempest, drawn with the pen and partly washed with Indian ink, from the Royal library, Windsor Castlesee text Nos. 606 and 608                                                                                                                                                                                                                                                                                                                                                                                                                                 |                             |
| [Pl. XXXV](pl035.htm#img_pl035.md).    | Three Drawings, from the Royal Library, Windsor Castle: No. 1 Sketches referring to the theory of the Proportions of the Human Figure--see text No. 348--; Nos. 2 and 3 referring to the representation of the Deluge--see text Nos. 608 and 609                                                                                                                                                                                                                                                                                                                                   |                             |
| [Pl. XXXVI](pl036.htm#img_pl036).   | Representation of Natural Phenomena; from the Royal Library, Windsor Castle--see text [p. 307](0608.htm#page_307.md), note, and No. 477                                                                                                                                                                                                                                                                                                                                                                                                                                               |                             |
| [Pl. XXXVII](pl037.htm#img_pl037).  | Representation of Natural Phenomena; from the Royal Library, Windsor Castle--see text [p. 307](0608.htm#page_307.md), note, and No. 477                                                                                                                                                                                                                                                                                                                                                                                                                                               |                             |
| [Pl. XXXVIII](pl038.htm#img_pl038). | Three Drawings: No. 1 Representation of Natural Phenomena, from the Codex Atlanticus, Milan--see text No 610--; No. 2 Sketch of a Male Figure from the Ashburnham MS. I--see text No. 579--; No. 3 Sketch of Male Figures, from the Royal Library, Windsor Castle--see [p. 340](dv10738.htm#page_340.md)                                                                                                                                                                                                                                                                              |                             |
|                                     | <span id="page_xxviii">p. xxviii</span>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                             |
| [Pl. XXXIX](pl039.htm#img_pl039).   | Charcoal Drawing, representing a Deluge, from the Royal Library, Windsor Castle,--see [p. 309](0608.htm#page_309.md), note                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                             |
| [Pl. XL](pl040.htm#img_pl040).      | Three Drawings from the Royal Library, Windsor Castle: No. 1 Representations of Natural Phenomena, drawn with the pen and washed with Indian ink--see text Nos. 473, 608-610--; No. 2 Sketches of Male Heads in red chalk, illustrating the practice of Figure Painting--see text No. 573--;No. 3 Sketch for a Madonna picture, drawn with the silverpoint on bluish-tinted paper--see text page [343](0663.htm#page_343.md), note                                                                                                                                                    |                             |
| [Pl. XLI](pl041.htm#img_pl041.md).     | Five Drawings illustrating the theory of Painting: No. 1 from the Ashburnham Manuscript I--see text Nos. 142 and 344--; No. 2 from the Codex Atlanticus, Milan--see text No. 200--; Nos. 3 and 4 from MS. F, Institut de France, Paris--see text No. 244;--No. 5 from MS. E, Institut de France, Paris--see text Nos. 197 and 1190                                                                                                                                                                                                                                                 |                             |
| [Pl. XLII](pl042.htm#img_pl042).    | A Female Head, preparatory Drawing in silverpoint, on brown-toned paper for the Angel in the picture "La Vierge aux Rochers"; from the Royal Library, Turin--see [p. 344](0663.htm#page_344.md)                                                                                                                                                                                                                                                                                                                                                                                       |                             |
| [Pl. XLIII](pl043.htm#img_pl043).   | Preparatory Study of Drapery for the same figure, done with the brush and Indian ink on greenish paper, the lights heightened with white; from the Royal Library, Windsor Castle--see pp. [344](0663.htm#page_344), [345](0664.htm#page_345.md) note                                                                                                                                                                                                                                                                                                                                  |                             |
| [Pl. XLIV](pl044.htm#img_pl044).    | Bust of a Boy, Study, in red chalk, for the figure of the Infant Christ in the same picture; from the Royal Library, Windsor Castle --see [p. 345](0664.htm#page_345.md) note                                                                                                                                                                                                                                                                                                                                                                                                         |                             |
|                                     | The Wall-Painting of the Last Supper, at Milan, woodcut page                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | [334](dv10738.htm#page_334.md) |
| [Pl. XLV](pl045.htm#img_pl045).     | Preparatory Sketch for the painting of the Last Supper; from the Royal Library, Windsor Castle--see [p. 335](dv10738.htm#page_335.md)                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                             |
| [Pl. XLVI](pl046.htm#img_pl046.md).    | Preparatory Sketch for the painting of the Last Supper drawn in red chalk; from the Accademia, Venice--see text No. 668                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                             |
| [Pl. XLVII](pl047.htm#img_pl047).   | Study for the Head of St. Matthew in the painting of the Last Supper, drawn in red chalk; from the Royal Library, Windsor Castle--see [p. 333](dv10738.htm#page_333.md)                                                                                                                                                                                                                                                                                                                                                                                                               |                             |
| [Pl. XLVIII](pl048.htm#img_pl048).  | Study, in black chalk, for the Head of St. Philip in the same picture; from the Royal Library, Windsor Castle--see [p. 333](dv10738.htm#page_333.md)                                                                                                                                                                                                                                                                                                                                                                                                                                  |                             |
| [Pl. XLIX](pl049.htm#img_pl049).    | Study, in charcoal, for St. Peter's right Arm in the same picture; from the Royal Library, Windsor Castle--see [p. 333](dv10738.htm#page_333.md)                                                                                                                                                                                                                                                                                                                                                                                                                                      |                             |
| [Pl. L](pl050.htm#img_pl050).       | Study, in red chalk, for the Head of Judas in the same picture; from the Royal Library, Windsor Castle--see [p. 333](dv10738.htm#page_333.md)                                                                                                                                                                                                                                                                                                                                                                                                                                         |                             |
|                                     | Raphael's Sketch after Leonardo's Cartoon of the Battle of Anghiari from the University Galleries, Oxford--see [p. 336](dv10738.htm#page_336) foll. on page                                                                                                                                                                                                                                                                                                                                                                                                                        | [337](dv10738.htm#page_337.md) |
|                                     | Study of two Heads of fighting Warriors, for the painting of the Battle of Anghiari, drawn in black chalk; from the Museum at Buda-Pesth--see [p. 340](dv10738.htm#page_340) on page                                                                                                                                                                                                                                                                                                                                                                                               | [338](dv10738.htm#page_338.md) |
|                                     | Study for a fighting Warrior, for the same painting, drawn in red chalk; from the Museum at Buda-Pesth,--see [p. 340](dv10738.htm#page_340) on page                                                                                                                                                                                                                                                                                                                                                                                                                                | [339](dv10738.htm#page_339.md) |
| [Pl. LI](pl051.htm#img_pl051).      | Drawing of the Head of a Criminal (the original in red chalk); from the Royal Library, Windsor Castle--see [p. 333](dv10738.htm#page_333.md)                                                                                                                                                                                                                                                                                                                                                                                                                                          |                             |
|                                     | Study of the Head of St. John in the painting of "La Vierge aux Rochers" in the Louvre, Paris--see [p. 344](0663.htm#page_344), [345](0664.htm#page_345), note on page                                                                                                                                                                                                                                                                                                                                                                                                             | [342](0663.htm#page_342.md)    |
|                                     | The picture of "La Vierge aux Rochers" in the Louvre, Paris, woodcut on page                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | [344](0663.htm#page_344.md)    |
|                                     | <span id="page_xxix">p. xxix</span>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                             |
| [Pl. LII](pl052.htm#img_pl052).     | Two Drawings: No. 1 Group of Figures, in silverpoint on reddish-toned paper, from the Royal Library, Windsor Castle--see Nos. 665, 666 note and 594 note; No. 2, Sketch of Horsemen fighting, Study for the cartoon of the Battle of Anghiari; from the British Museum, London--see [p. 336](dv10738.htm#page_336.md)                                                                                                                                                                                                                                                                 |                             |
| [Pl. LIII](pl053.htm#img_pl053).    | Study for the Cartoon of the Battle of Anghiari; drawing from the Accademia, Venice--see [p. 336](dv10738.htm#page_336.md)                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                             |
| [Pl. LIV](pl054.htm#img_pl054).     | Study for the cartoon of the Battle of Anghiari; drawing from the Accademia, Venice--see [p. 336](dv10738.htm#page_336.md)                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                             |
| [Pl. LV](pl055.htm#img_pl055).      | Study for the Cartoon of the Battle of Anghiari, drawing from the Accademia, Venice--see [p. 337](dv10738.htm#page_337.md)                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                             |
| [Pl. LVI](pl056.htm#img_pl056).     | Study in black chalk for the Cartoon of the battle of Anghiari, in the Royal Library, Windsor Castle--see [p. 338](dv10738.htm#page_338.md)                                                                                                                                                                                                                                                                                                                                                                                                                                           |                             |
| [Pl. LVII](pl057.htm#img_pl057).    | Cesare da Sesto's Copy of part of the Cartoon of the Battle of Anghiari; charcoal Drawing from the Royal Library, Windsor Castle--see [p. 337](dv10738.htm#page_337.md)                                                                                                                                                                                                                                                                                                                                                                                                               |                             |
| [Pl. LVIII](pl058.htm#img_pl058.md).   | Studies for Allegorical Compositions; from the Royal Library, Windsor Castle--see text No. 672, note                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |                             |
| [Pl. LIX](pl059.htm#img_pl059.md).     | Drawing of an Allegorical Composition; from the Library of Christ Church College, Oxford--see text No. 676                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |                             |
| [Pl. LX](pl060.htm#img_pl060.md).      | Four Drawings of Allegorical Representations: No. 1 from the Library of Christ Church College, Oxford--see text No. 676--; No. 2-4 from Manuscript M, Institut de France, Paris--see text Nos. 699-701                                                                                                                                                                                                                                                                                                                                                                             |                             |
| [Pl. LXI](pl061.htm#img_pl061.md).     | Allegorical Composition, from the Library of Christ Church College, Oxford--see text No. 677                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                             |
| [Pl. LXII](pl062.htm#img_pl062.md).    | Two Drawings: No. r Portrait of Bernardo di Bandino, when hanged; in the possession of Mons. Thibaudeau, London--see text No. 664--; No. 2: Emblems, from the Royal Library, Windsor Castle--see text No. 681                                                                                                                                                                                                                                                                                                                                                                      |                             |
| [Pl. LXIII](pl063.htm#img_pl063.md).   | Studies of Emblems; from the Royal Library, Windsor Castle--see text No. 684                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                             |
| [Pl. LXIV](pl064.htm#img_pl064.md).    | Emblematic Representation; from the Royal Library, Windsor Castle--see text No. 688                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                             |

------------------------------------------------------------------------

[Next: Introduction](v1intro.md)
