[![](../../cdshop/ithlogo.png)](../../index.md)  
[Intangible Textual Heritage](../../index)  [Australia](../index.md) 
[Index](index)  [Previous](ntca01)  [Next](ntca03.md) 

------------------------------------------------------------------------

*The Native Tribes of North Central Australia*, by Baldwin Spencer and
F. J. Gillen \[1899\], at Intangible Textual Heritage

------------------------------------------------------------------------

<span id="page_xiii">p. xiii</span>

## List of Illustrations

<div align="center">

|                                                                                                                                                                                                                                                                            |                                          |     |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------|-----|
| FIG.                                                                                                                                                                                                                                                                       | PAGE                                     |     |
| 1\. Outline Map of the Central Area, showing the Distribution of the Tribes referred to                                                                                                                                                                                    | 3                                        |     |
| 2\. Group of Old Men at a Wurley                                                                                                                                                                                                                                           | 13                                       |     |
| 3\. Members of a Family of Arunta Natives, showing the Wurley, Weapons and Implements used in daily life                                                                                                                                                                   | 17                                       |     |
| 4\. Spear Throwing                                                                                                                                                                                                                                                         | 18                                       |     |
| 5\. Spear Throwing                                                                                                                                                                                                                                                         | 19                                       |     |
| 6\. Boomerang Throwing                                                                                                                                                                                                                                                     | 21                                       |     |
| 7\. Arunta Native, side face                                                                                                                                                                                                                                               | 29                                       |     |
| 8\. Arunta Native, full face                                                                                                                                                                                                                                               | 31                                       |     |
| 9\. Arunta Native, old man                                                                                                                                                                                                                                                 | 33                                       |     |
| 10\. Arunta Native, to show the frizzly nature of the beard                                                                                                                                                                                                                | 35                                       |     |
| 11\. Arunta Native, to show the wavy nature of the hair                                                                                                                                                                                                                    | 39                                       |     |
| 12\. Group of Warramunga Men, four of the older ones have the upper lip bare                                                                                                                                                                                               | 41                                       |     |
| 13\. Young Women, Arunta Tribe, side face                                                                                                                                                                                                                                  | 43                                       |     |
| 14\. Young Women, Arunta Tribe, full face                                                                                                                                                                                                                                  | 45                                       |     |
| 15\. Young Woman, Arunta, showing body scars and tooth knocked out                                                                                                                                                                                                         | 47                                       |     |
| 16\. Old Woman, Arunta Tribe                                                                                                                                                                                                                                               | 49                                       |     |
| 17\. Young Woman, Warramunga Tribe                                                                                                                                                                                                                                         | 51                                       |     |
| 18\. Woman carrying Child, Arunta Tribe                                                                                                                                                                                                                                    | 53                                       |     |
| 19\. Diagram of Marriage System in the Dieri Tribe                                                                                                                                                                                                                         | 109                                      |     |
| 20\. Wooden Churinga or Sacred Sticks of the Urabunna, Luritcha and Arunta Tribes                                                                                                                                                                                          | 129                                      |     |
| 21\. Stone Churinga of the Arunta, Kaitish and Warramunga Tribes                                                                                                                                                                                                           | 131                                      |     |
| 22\. Sacred Objects of the Waaga Tribe                                                                                                                                                                                                                                     | 158<span id="page_xiv">p. xiv</span>     |     |
| 23\. Churinga which have just been returned after having been borrowed. During the performance of ceremonies they are placed on the small platform built in the tree                                                                                                       | 163                                      |     |
| 24\. Sacred Drawings of the Witchetty Grub Totem on the rocks at the Emily Gap                                                                                                                                                                                             | 171                                      |     |
| 25\. The Great Ilthura where Intichiuma was performed at the Emily Gap                                                                                                                                                                                                     | 173                                      |     |
| 26\. Rubbing the Stomach with the Churinga Uchaqua during the Intichiuma Ceremony of the Witchetty Grub Totem. The men are sitting in one of the Ilthura                                                                                                                   | 174                                      |     |
| 27\. Rubbing the Stomach with the Churinga Unchima during the Intichiuma Ceremony of the Witchetty Grub Totem. The men are sitting in one of the Ilthura                                                                                                                   | 175                                      |     |
| 28\. The Alatunja returning to Camp after the Intichiuma ceremony of the Witchetty Grub Totem at the Emily Gap                                                                                                                                                             | 177                                      |     |
| 29\. Group of Men of the Emu Totem sitting round the Churinga Ilpintira, which is drawn on the ground                                                                                                                                                                      | 181                                      |     |
| 30\. Preparing Decorations for the performance of the Intichiuma Ceremony of the Emu Totem                                                                                                                                                                                 | 182                                      |     |
| 31\. Performance of the Intichiuma Ceremony of the Unjiamba Totem. Pouring blood on to the stone                                                                                                                                                                           | 184                                      |     |
| 32\. Intichiuma Ceremony of Water Totem                                                                                                                                                                                                                                    | 190                                      |     |
| 33\. Undiara, where the Intichiuma Ceremony of the Kangaroo Totem is performed                                                                                                                                                                                             | 195                                      |     |
| 34\. First Ceremony of Initiation, painting and throwing the boys up in the air                                                                                                                                                                                            | 216                                      |     |
| 35\. First Ceremony of Initiation, painting and throwing the boys up in the air                                                                                                                                                                                            | 217                                      |     |
| 36\. Diagram of the Apulla Ground                                                                                                                                                                                                                                          | 219                                      |     |
| 37\. Ceremony of the Kangaroo Totem, men lying down on the top of the Wurtja                                                                                                                                                                                               | 224                                      |     |
| 38\. Ceremony of Kangaroo Totem, the two men standing up wear small Waningas; the man lying down is supposed to be a dog                                                                                                                                                   | 225                                      |     |
| 39\. The Wurtja embracing the Waninga, which has been used during a Ceremony of the Rat Totem                                                                                                                                                                              | 233                                      |     |
| 40\. The Wurtja crouching behind his brake; on his back is a design of the Snake Totem; the Apulla lines are seen with the Group of Men in front of their brake; the man who will perform the operation of circumcision is on the left and his assistant on the right side | 235<span id="page_xv">p. xv</span>       |     |
| 41\. Women stripping the poles, just before the Ceremony of Lartna in the Northern Arunta Tribe                                                                                                                                                                            | 245                                      |     |
| 42\. The operator and his assistant standing in position during the performance of Lartna. The operator holds the small stone knife in his right hand                                                                                                                      | 247                                      |     |
| 43\. Immediately before the Ceremony of Ariltha; the two Arakurta embracing the Nurtunja, which has been used during a ceremony of the Bandicoot Totem                                                                                                                     | 254                                      |     |
| 44\. Immediately after the Ceremony of Ariltha; the two Ertwakurka sitting on the Shields                                                                                                                                                                                  | 255                                      |     |
| 45\. Old Men in charge of the Store of Churinga belonging to the Purula and Kumara, during the Engwura Ceremony. The Churinga are stored on a platform called Thanunda                                                                                                     | 273                                      |     |
| 46\. Plan of the Engwura Ground                                                                                                                                                                                                                                            | 276                                      |     |
| 47\. Iruntarinia Ceremony of the Unjiamba Totem: the long cord represents the path of the Wild Cat men as they travelled along in the Alcheringa                                                                                                                           | 287                                      |     |
| 48\. Ceremony of the Wild Cat Totem, showing the laying on of hands to cause the performers to stop                                                                                                                                                                        | 289                                      |     |
| 49\. Group of Men examining the Churinga                                                                                                                                                                                                                                   | 291                                      |     |
| 50\. Ceremony of the Ulpmerka of Quiurnpa                                                                                                                                                                                                                                  | 292                                      |     |
| 51\. Ceremony of the Plum Tree Totem: the performer is supposed to be eating plums                                                                                                                                                                                         | 293                                      |     |
| 52\. Iruntarinia Ceremony of the Eagle-Hawk Totem                                                                                                                                                                                                                          | 295                                      |     |
| 53\. Ceremony of Unjiamba Totem of Ooraminna                                                                                                                                                                                                                               | 297                                      |     |
| 54\. Ceremony of the Wild Cat Totem of Arapera, to illustrate one form of Nurtunja                                                                                                                                                                                         | 299                                      |     |
| 55\. Ceremony of the Ulpmerka of the Plum Tree Totem of Quiurnpa, to illustrate one form of Nurtunja                                                                                                                                                                       | 301                                      |     |
| 56\. Ceremony of the large Lizard Totem: the two undecorated men represent Thippa - thippa Men who changed into Birds                                                                                                                                                      | 305                                      |     |
| 57\. Ceremony of the Water Totem, showing how the Waninga is carried                                                                                                                                                                                                       | 307                                      |     |
| 58\. Ceremony of the Ulpmerka of the Grass Seed Totem, to illustrate one form of Nurtunja                                                                                                                                                                                  | 311                                      |     |
| 59\. Ceremony of the Ulpmerka of the Plum Tree Totem of Quiurnpa. The man sitting down wears a special form of Nurtunja on his head                                                                                                                                        | 314                                      |     |
| 60\. Ceremony of the Fish Totem of Uratinga on the Finke River                                                                                                                                                                                                             | 317<span id="page_xvi">p. xvi</span>     |     |
| 61\. Ceremony of the Irriakura Totem of Umbanjun, the decorated feathers on the head represent the flowering Irriakura                                                                                                                                                     | 319                                      |     |
| 62\. Ceremony of the Irriakura Totem of Oknirchumpatana. The performer sits in front of a series of tufts of feathers fixed in the ground                                                                                                                                  | 321                                      |     |
| 63\. Ceremony of an Ant Totem of Alkniwukulla, to illustrate one form of Nurtunja; the lines of down represent roots of wattle trees, amongst which the women dig for ants; the performers represent women                                                                 | 325                                      |     |
| 64\. Iruntarinia Ceremony of the Unjiamba Totem, to illustrate one form of Nurtunja; the small cross pieces represent pointing sticks                                                                                                                                      | 327                                      |     |
| 65\. Ceremony representing two Oruncha of Kulparra                                                                                                                                                                                                                         | 330                                      |     |
| 66\. Ceremony of the Oruncha of Chauritchi                                                                                                                                                                                                                                 | 332                                      |     |
| 67\. An Oruncha Ceremony: the performers coming on to the ground                                                                                                                                                                                                           | 333                                      |     |
| 68\. Iruntarinia Ceremony of the Unjiamba Totem of Apera-na-Unkumna, to illustrate one form of Nurtunja                                                                                                                                                                    | 335                                      |     |
| 69\. The Erathipa Stone, showing the hole through which the Spirit Children emerge, and the charcoal line painted above it                                                                                                                                                 | 337                                      |     |
| 70\. Ceremony of the Opossum Totem of Arimurla, to illustrate one form of Nurtunja                                                                                                                                                                                         | 339                                      |     |
| 71\. Ceremony of the Opossum Totem of Arimurla, to illustrate one form of Nurtunja                                                                                                                                                                                         | 340                                      |     |
| 72\. Preparing for a Ceremony of the Frog Totem of Imanda                                                                                                                                                                                                                  | 342                                      |     |
| 73\. Ceremony of the Emu Totem; the head-dress represents the neck and head of an Emu                                                                                                                                                                                      | 343                                      |     |
| 74\. Ceremony of the Frog Totem of Imanda                                                                                                                                                                                                                                  | 345                                      |     |
| 75\. Ceremony of the Frog Totem of Imanda                                                                                                                                                                                                                                  | 346                                      |     |
| 76\. The Women throwing fire over the Illpongwurra                                                                                                                                                                                                                         | 349                                      |     |
| 77\. The Illpongwurra lying down with their heads on the Parra, behind which are stacked the bushes which they carry when returning to camp                                                                                                                                | 353                                      |     |
| 78\. Dance of the Illpongwurra round the performers of a ceremony; this running round is called Wahkutnima                                                                                                                                                                 | 355                                      |     |
| 79\. Preparing the fire for the Illpongwurra                                                                                                                                                                                                                               | 357                                      |     |
| 80\. Ingwurninga Inkinja Ceremony of the Emu Totem of Imanda                                                                                                                                                                                                               | 359                                      |     |
| 81\. Ceremony of the Kangaroo Totem of Undiara, to illustrate one form of Nurtunja                                                                                                                                                                                         | 361                                      |     |
| 82\. Ceremony of the Kangaroo Totem of Undiara, to illustrate one form of Nurtunja                                                                                                                                                                                         | 363                                      |     |
| 83\. Ambilyerikirra Ceremony                                                                                                                                                                                                                                               | 367<span id="page_xvii">p. xvii</span>   |     |
| 84\. The erection of the Sacred Pole, or Kauaua; the man who has climbed up is arranging the Churinga                                                                                                                                                                      | 371                                      |     |
| 85\. The Illpongwurra on the fire                                                                                                                                                                                                                                          | 373                                      |     |
| 86\. Ceremony of the Frog Totem of Imanda                                                                                                                                                                                                                                  | 375                                      |     |
| 87\. Totemic Designs painted on the backs of the Illpongwurra                                                                                                                                                                                                              | 377                                      |     |
| 88\. The Illpongwurra gathered round the Kauaua                                                                                                                                                                                                                            | 379                                      |     |
| 89\. Ceremony of releasing from the Ban of Silence; touching the mouths of the younger men with a sacred object                                                                                                                                                            | 383                                      |     |
| 90\. Ceremony of releasing from the Ban of Silence; touching the mouth of the younger man with a fragment of the food presented by him to the older man                                                                                                                    | 385                                      |     |
| 91\. Rocks at Quiurnpa which arose to mark the spot where the Illpongwurra were burnt during the Engwura                                                                                                                                                                   | 391                                      |     |
| 92\. The Nanja rock of Kukaitcha, the leader of the Ulpmerka men of the Plum Tree Totem at Quiurnpa                                                                                                                                                                        | 393                                      |     |
| 93\. Emily Gap from the South side                                                                                                                                                                                                                                         | 426                                      |     |
| 94\. Emily Gap from the North side                                                                                                                                                                                                                                         | 427                                      |     |
| 95\. Ceremony of the White Bat Totem concerned with Cannibalism                                                                                                                                                                                                            | 474                                      |     |
| 96\. Emu Feather Shoes worn by the Kurdaitcha                                                                                                                                                                                                                              | 479                                      |     |
| 97\. Kurdaitcha creeping up to his enemy                                                                                                                                                                                                                                   | 482                                      |     |
| 98\. Illapurinja Woman                                                                                                                                                                                                                                                     | 487                                      |     |
| 99\. Tree Burial in the Warramunga Tribe                                                                                                                                                                                                                                   | 499                                      |     |
| 100\. Widow smeared with Kaolin and wearing the Chimurilia                                                                                                                                                                                                                 | 501                                      |     |
| 101\. Chimurilia, fur string bands and feathers worn by the Widow during the Urpmilchima Ceremony at the Grave                                                                                                                                                             | 505                                      |     |
| 102\. Iruntarinia Ceremony of the Unjiamba (Hakea Tree) Totem of Urthipita, showing the Umbalinyara Cross                                                                                                                                                                  | 518                                      |     |
| 103\. Iruntarinia Ceremony concerned with two Oruncha of Atnurtinya Kinya                                                                                                                                                                                                  | 520                                      |     |
| 104\. Medicine Man showing the hole made in his tongue                                                                                                                                                                                                                     | 524                                      |     |
| 105\. Medicine Man made by the Oruncha, with the Oruncha Marilla, or design of the Oruncha                                                                                                                                                                                 | 527                                      |     |
| 106\. Various forms of Implements of Magic used amongst the Central Tribes                                                                                                                                                                                                 | 535                                      |     |
| 107\. Drawing intended to represent a Woman lying on her back                                                                                                                                                                                                              | 549                                      |     |
| 108\. Ceremony of the Sun Totem of Ilparlinja                                                                                                                                                                                                                              | 563                                      |     |
| 109\. Clothing and Personal Ornaments                                                                                                                                                                                                                                      | 569                                      |     |
| 110\. Personal Ornaments                                                                                                                                                                                                                                                   | 571                                      |     |
| 110A. Various forms of Spear-heads                                                                                                                                                                                                                                         | 576                                      |     |
| 111\. Spear-throwers                                                                                                                                                                                                                                                       | 579<span id="page_xviii">p. xviii</span> |     |
| 112\. Construction of the Tassel or Fringe of the Nulliga                                                                                                                                                                                                                  | 580                                      |     |
| 113\. Attachment of the Tassel to the Nulliga                                                                                                                                                                                                                              | 580                                      |     |
| 114\. Fire making, by means of rubbing the edge of a Spear-thrower on a Shield                                                                                                                                                                                             | 584                                      |     |
| 115\. Shields                                                                                                                                                                                                                                                              | 585                                      |     |
| 116\. Shields                                                                                                                                                                                                                                                              | 585                                      |     |
| 117\. Stone Axes and Knives                                                                                                                                                                                                                                                | 589                                      |     |
| 118\. Boomerangs                                                                                                                                                                                                                                                           | 597                                      |     |
| 118A. Ornamentation of large Boomerangs                                                                                                                                                                                                                                    | 598                                      |     |
| 118B. Fighting Clubs                                                                                                                                                                                                                                                       | 603                                      |     |
| 119\. Various Implements                                                                                                                                                                                                                                                   | 605                                      |     |
| 120\. Pitchis                                                                                                                                                                                                                                                              | 609                                      |     |
| 121\. Pitchis                                                                                                                                                                                                                                                              | 609                                      |     |
| 122\. Structure of the String Bag                                                                                                                                                                                                                                          | 612                                      |     |
| 123\. Arunta Native using Spindle for making Fur-string                                                                                                                                                                                                                    | 613                                      |     |
| 124\. Native Rock Paintings                                                                                                                                                                                                                                                | *To face page* 615                       |     |
| 125\. Arunta Natives, Corrobboree Decorations                                                                                                                                                                                                                              | 619                                      |     |
| 126\. Arunta Natives, Corrobboree Decorations                                                                                                                                                                                                                              | 619                                      |     |
| 127\. Arunta Natives, decorated for the Erkita Corrobboree                                                                                                                                                                                                                 | 620                                      |     |
| 128\. Decorations used during a Rain Dance or Corrobboree, Arunta Tribe                                                                                                                                                                                                    | 621                                      |     |
| 129\. Old Man instructing Boys how to perform a Corrobboree                                                                                                                                                                                                                | 622                                      |     |
| 130\. Preparing for the Erkita Corrobboree, Arunta Tribe                                                                                                                                                                                                                   | 623                                      |     |
| 131\. Churingia Ilkinia or Sacred Rock Drawing of a Group of the Honey Ant Totem in the Warramunga Tribe                                                                                                                                                                   | *To face page* 631                       |     |
| 132\. Churinga Ilkinia of the Udnirringita Totem drawn on the Rocks at the Emily Gorge                                                                                                                                                                                     | *To face page* 632                       |     |
| 133\. Churinga Ilkinia of the Ulpmerka of the Plum Tree Totem, drawn on the Rocks at Quiurnpa                                                                                                                                                                              | *To face page* 633                       |     |
| MAPS                                                                                                                                                                                                                                                                       |                                          |     |
| 1\. Outline Map of the Central Area of Australia showing the tracks followed by the four groups of Achilpa and the spots at which they camped                                                                                                                              | *Inside back cover*                      |     |
| 2\. Outline Map of the Central Area of Australia in the region of the MacDonnell Range, showing the tracks followed by the various groups of Udnirringita and of Emu men, together with the spots at which they camped, and other localities concerned with traditions     | *Inside back cover*                      |     |

</div>

 

------------------------------------------------------------------------

[Next: Chapter I. Introduction](ntca03.md)
