[![](../../cdshop/ithlogo.png)](../../index.md)  
[Intangible Textual Heritage](../../index)  [Judaism](../index.md) 
[Index](index)  [Previous](tbr07)  [Next](tbr09.md) 

------------------------------------------------------------------------

*Tractate Berakoth*, by , by A. Lukyn Williams, \[1921\], at Intangible
Textual Heritage

------------------------------------------------------------------------

### 6. SYNOPSIS OF CONTENTS

(*M*. = Mishna: *T*. = Tosephta.)

|                                                                                                         |                                                                                                                                                          |                         |
|---------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------|
|                                                                                                         |                                                                                                                                                          | PAGE                    |
| I.                                                                                                      | *The Shma‘*: *M*. i.-iii.; *T*. i., ii.                                                                                                                  |                         |
|                                                                                                         | In the evening: *M*. i. 1-3 (1); *T*. i. 1.                                                                                                              | [1](tbr10.htm#page_1.md)   |
|                                                                                                         | In the morning: *M*. i. 4 (2); *T*. i. 2                                                                                                                 | [4](tbr11.htm#page_4.md)   |
|                                                                                                         | Posture: *M*. i. 5, 6 (3); *T*. i. 4                                                                                                                     | [5](tbr11.htm#page_5.md)   |
|                                                                                                         | The Benedictions connected with the Shma‘. Long and short forms: *M*. i. 7 (4); *T*. i. 5                                                                | [7](tbr12.htm#page_7.md)   |
|                                                                                                         | Excursus on various forms and on bending forward: *T*. i. 6-9                                                                                            | [8](tbr13.htm#page_8.md)   |
|                                                                                                         | The Going forth from Egypt must be said at the evening Shma‘ also: *M*. i. 8 (5); *T*. i. 50, 11; ii., 1                                                 | [10](tbr14.htm#page_10.md) |
|                                                                                                         |    With Excursus on the Bible use of phrases that had apparently been superseded: *T*. i. 10-15                                                          | [10](tbr14.htm#page_10.md) |
|                                                                                                         | <span id="page_xxi">p. xxi</span>                                                                                                                        |                         |
|                                                                                                         |                                                                                                                                                          | PAGE                    |
|                                                                                                         | On reciting the Shma‘ with intention: *M*. ii. 1<sup>a</sup>; *T*. ii. 2                                                                                 | [14](tbr14.htm#page_14.md) |
|                                                                                                         | On saluting between the sections: *M*. ii. 1<sup>b</sup>                                                                                                 | [14](tbr14.htm#page_14.md) |
|                                                                                                         | The sections of the Shma‘ and their order: *M*. ii. 2, 3 (2)                                                                                             | [15](tbr15.htm#page_15.md) |
|                                                                                                         | May the recitation be inaudible, or said erroneously: M ii. 4 (3); *T*. ii. 3-5                                                                          | [16](tbr16.htm#page_16.md) |
|                                                                                                         | On interrupting tasks to recite the Shma‘, etc.: *T*. ii. 6, 7                                                                                           | [17](tbr17.htm#page_17.md) |
|                                                                                                         | Workmen may recite on the top of a tree or on a scaffold: *M*. ii. 5 (4); *T*. ii. 8                                                                     | [18](tbr17.htm#page_18.md) |
|                                                                                                         | Labourers may not lead in the synagogue: *T*. ii. 9                                                                                                      | [19](tbr18.htm#page_19.md) |
|                                                                                                         | A bridegroom exempt—R. Gamaliel: *M*. ii. 6 (5); *T*. i. 3                                                                                               | [19](tbr18.htm#page_19.md) |
|                                                                                                         | The case of marriage-guests: *T*. ii. 10                                                                                                                 | [20](tbr19.htm#page_20.md) |
|                                                                                                         | R. Gamaliel again—when mourning for his wife: *M*. ii. 7 (6)                                                                                             | [20](tbr19.htm#page_20.md) |
|                                                                                                         | R. Gamaliel again receives condolence for the death of his servant: *M*. ii. 8 (7)                                                                       | [21](tbr20.htm#page_21.md) |
|                                                                                                         | A bridegroom may recite, but should beware of ostentation: *M*. ii. 9 (8)                                                                                | [21](tbr20.htm#page_21.md) |
|                                                                                                         | The Shma‘ and mourners at a funeral: *M*. iii. 1                                                                                                         | [21](tbr20.htm#page_21.md) |
|                                                                                                         | And on the return from it: *M*. iii. 2; *T*. ii. 11                                                                                                      | [22](tbr22.htm#page_22.md) |
|                                                                                                         | The case of women, slaves, and children: *M*. iii. 3                                                                                                     | [23](tbr23.htm#page_23.md) |
|                                                                                                         | The cases of those ceremonially unclean men and women: *M*. iii. 4-6; *T*. ii. 12, 13                                                                    | [23](tbr23.htm#page_23.md) |
|                                                                                                         | Against unseemliness in reciting the Shma‘: *T*. ii. 14-21                                                                                               | [25](tbr25.htm#page_25.md) |
|                                                                                                         | * *                                                                                                                                                      |                         |
| II\.                                                                                                    | *Prayer, especially the Prayer* par excellence (*the Eighteen Benedictions*): *M*. iv. and v.; *T*. iii.                                                 |                         |
|                                                                                                         | The three times of prayer: *M*. iv. i.; *T*. iii. i-3                                                                                                    | [28](tbr25.htm#page_28.md) |
|                                                                                                         | The prayer of R. Nechuniah on entering and on leaving the Lecture Hall: *M*. iv. 2                                                                       | [30](tbr27.htm#page_30.md) |
|                                                                                                         | The Eighteen, and their abstract: *M*. iv. 3                                                                                                             | [30](tbr27.htm#page_30.md) |
|                                                                                                         | The Prayer not to be regarded as a mechanical unit: *M*. iv. 4<sup>a</sup>                                                                               | [31](tbr28.htm#page_31.md) |
|                                                                                                         | The Prayer in time of danger: *M*. iv. 4<sup>b</sup>; *T*. iii. 7                                                                                        | [31](tbr28.htm#page_31.md) |
|                                                                                                         | The Prayer when one is riding on an ass: *M*. iv. 5; *T*. 18                                                                                             | [32](tbr29.htm#page_32.md) |
|                                                                                                         | Or when one is in a ship or on a raft: *M*. iv. 6; *T*. iii. 19                                                                                          | [32](tbr29.htm#page_32.md) |
|                                                                                                         | The Additional Prayers: *M*. iv. 7; *T*. iii. 10-13                                                                                                      | [33](tbr31.htm#page_33.md) |
|                                                                                                         | The posture, and attention, in the Prayer: *M*. v. i; *T*. iii. 4-6, 14-17, 20, 21                                                                       | [35](tbr32.htm#page_35.md) |
|                                                                                                         | The mention of, and the petition for, rain, also the *Habdalah*—in the Prayer: *M*. v. 2; *T*. iii. 9                                                    | [39](tbr33.htm#page_39.md) |
|                                                                                                         | Examples of over-zeal: *M*. v. 3<sup>a</sup>                                                                                                             | [40](tbr34.htm#page_40.md) |
|                                                                                                         | <span id="page_xxii">p. xxii</span>                                                                                                                      |                         |
|                                                                                                         |                                                                                                                                                          | PAGE                    |
|                                                                                                         | The leader: *M*. v. 3<sup>b</sup>                                                                                                                        | [40](tbr34.htm#page_40.md) |
|                                                                                                         |    To avoid occasions for making mistakes: *M*. v. 4                                                                                                     | [41](tbr35.htm#page_41.md) |
|                                                                                                         |    Fluency a sign of acceptance: *M*. v. 5                                                                                                               | [41](tbr35.htm#page_41.md) |
|                                                                                                         | *Additional matter in* *T*.                                                                                                                              |                         |
|                                                                                                         |    Reverence in writing the Name: *T*. iii. 22                                                                                                           | [42](tbr36.htm#page_42.md) |
|                                                                                                         |    On the Benediction of mourners: *T*. iii. 23, 24                                                                                                      | [42](tbr36.htm#page_42.md) |
|                                                                                                         |    On certain points about the Eighteen Benedictions: *T*. iii, 25                                                                                       | [42](tbr36.htm#page_42.md) |
|                                                                                                         |                                                                                                                                                          |                         |
| III\.                                                                                                   | *Benedictions at meals*, especially after meals, and on various occasions: *M*. vi.-ix.; *T*. v.-vii.                                                    |                         |
|                                                                                                         | The proper forms for the different foods: *M*. vi. 1-4; *T*. iv. 1-7                                                                                     | [43](tbr37.htm#page_43.md) |
|                                                                                                         | On one Benediction exempting another: *M*. vi. 5                                                                                                         | [47](tbr38.htm#page_47.md) |
|                                                                                                         | When the Benediction may be said by one person for all: *M*. vi. 6                                                                                       | [48](tbr40.htm#page_48.md) |
|                                                                                                         | The order of the meal: *T*. iv. 8-13                                                                                                                     | [48](tbr40.htm#page_48.md) |
|                                                                                                         | The position of the persons: *T*. v. 5                                                                                                                   | [50](tbr40.htm#page_50.md) |
|                                                                                                         | The order of washing the hands and mixing the cup: *T*. v. 6                                                                                             | [50](tbr40.htm#page_50.md) |
|                                                                                                         | Who partakes first: *T*. v. 7                                                                                                                            | [50](tbr40.htm#page_50.md) |
|                                                                                                         | Manners at table: *T*. v. 8, 9                                                                                                                           | [50](tbr40.htm#page_50.md) |
|                                                                                                         | Salted relish and the general Rule that the Benediction of the principal food suffices: *M*. vi. 7; *T*. iv. 14                                          | [51](tbr40.htm#page_51.md) |
|                                                                                                         | Illustrations of the principal food: *T*. iv. 16                                                                                                         | [51](tbr40.htm#page_51.md) |
|                                                                                                         |    And of the proper forms of Benediction: *T*. iv. 15, 16                                                                                               | [51](tbr40.htm#page_51.md) |
|                                                                                                         |    Parenthesis—Why did Judah deserve the kingdom? *T*. iv. 17, 18                                                                                        | [54](tbr40.htm#page_54.md) |
|                                                                                                         |    On interruptions during the meal: *T*. iv. 19-21                                                                                                      | [56](tbr40.htm#page_56.md) |
|                                                                                                         | On saying three Benedictions in certain cases: *M*. vi. 8                                                                                                | [57](tbr40.htm#page_57.md) |
|                                                                                                         | The entrance on the Sabbath, the meal and the Benedictions: *T*. v. 1-4                                                                                  | [57](tbr40.htm#page_57.md) |
|                                                                                                         | Who may be invited to partake in the Benediction after meals: *M*. vii. 1-3 (1, 2); *T*. v. 10, 14, 17, 18                                               | [59](tbr41.htm#page_59.md) |
|                                                                                                         | The case of one who has not actually eaten: *T*. v. 20                                                                                                   | [61](tbr43.htm#page_61.md) |
|                                                                                                         |    As to a sweet relish: *T*. v. 11                                                                                                                      | [61](tbr43.htm#page_61.md) |
|                                                                                                         |    And bread with dessert: *T*. v. 12                                                                                                                    | [61](tbr43.htm#page_61.md) |
|                                                                                                         |    On washing before and after a meal: *T*. v. 13                                                                                                        | [61](tbr43.htm#page_61.md) |
|                                                                                                         | The formula of invitation, depending on the number present: *M*. vii. 4, 5 (3<sup>a</sup>)                                                               | [62](tbr43.htm#page_62.md) |
|                                                                                                         |    And in the synagogue: *M*. vii. 6 (3<sup>b</sup>)                                                                                                     | [63](tbr44.htm#page_63.md) |
|                                                                                                         | Companies how to be divided: *M*. vii. 7 (4); *T*. v. 19                                                                                                 | [63](tbr44.htm#page_63.md) |
|                                                                                                         | On two companies in one house: *M*. vii. 8<sup>a</sup> (5<sup>a</sup>)                                                                                   | [64](tbr45.htm#page_64.md) |
|                                                                                                         | <span id="page_xxiii">p. xxiii</span>                                                                                                                    |                         |
|                                                                                                         |                                                                                                                                                          | PAGE                    |
|                                                                                                         | Whether the Benediction should be said over unmixed wine: *M*. vii. 8<sup>b</sup> (5<sup>b</sup>); *cf*. *T*. iv. 3, *infra*, [p. 45](tbr38.htm#page_45) | [64](tbr45.htm#page_64.md) |
|                                                                                                         | * *                                                                                                                                                      |                         |
| *Points on these subjects in dispute between the School of Shammai and of Hillel:* *M*. viii.; *T*. vi. |                                                                                                                                                          |                         |
|                                                                                                         | At the beginning of Sabbath or Feast-day the order of the Benedictions: *M*. viii. 1; *T*. vi. 1; iii. 8                                                 | [65](tbr47.htm#page_65.md) |
|                                                                                                         | On the order of washing the hands and mixing the cup; *M*. viii. 2; *T*. vi. 2                                                                           | [66](tbr47.htm#page_66.md) |
|                                                                                                         | On the order of tidying the room and washing [the](errata.htm#1) hands: *M*. viii. 3 (4); *T*. vi. 4                                                     | [67](tbr48.htm#page_67.md) |
|                                                                                                         | Where one lays the napkin after drying one's hands: *M*. viii. 4 (3); *T*. vi. 3                                                                         | [67](tbr48.htm#page_67.md) |
|                                                                                                         | Wine and oil: *T*. vi. 5                                                                                                                                 | [68](tbr50.htm#page_68.md) |
|                                                                                                         | The order of the Benedictions at the end of Sabbath: *M*. viii. 5 (5<sup>a</sup>); *T*. vi. 6                                                            | [68](tbr50.htm#page_68.md) |
|                                                                                                         | The wording of the Benediction over the lamp: *M*. viii. 6 (5<sup>b</sup>)                                                                               | [70](tbr52.htm#page_70.md) |
|                                                                                                         | Parenthesis—                                                                                                                                             |                         |
|                                                                                                         |    When Benedictions must not be said over lamp and spices: *M*. viii. 7 (6); *T*. vi. 7<sup>a</sup>                                                     | [70](tbr52.htm#page_70.md) |
|                                                                                                         |    Hybrids and fire . *T*. vi. 7<sup>b</sup>                                                                                                             | [71](tbr53.htm#page_71.md) |
|                                                                                                         |    Fire and spices of a bath—a spice shop: *T*. vi. 8.                                                                                                   | [75](tbr56.htm#page_75.md) |
|                                                                                                         | If the Benediction has been forgotten: *M*. viii. 8 (7)                                                                                                  | [72](tbr54.htm#page_72.md) |
|                                                                                                         | The order of the Benedictions over wine and food: *M*. viii. 9<sup>b</sup>, 8<sup>a</sup>                                                                | [72](tbr54.htm#page_72.md) |
|                                                                                                         |    When Amen may not be said: *M*. viii. 9<sup>b</sup> (8<sup>b</sup>); *T*. iii. 26; v. 51                                                              | [72](tbr54.htm#page_72.md) |
|                                                                                                         |    On sacrifices in Jerusalem: *T*. v. 22                                                                                                                | [73](tbr55.htm#page_73.md) |
|                                                                                                         |    On what constitutes a common meal on a journey: *T*. v. 23                                                                                            | [73](tbr55.htm#page_73.md) |
|                                                                                                         |    Workmen and their master: *T*. v. 24                                                                                                                  | [73](tbr55.htm#page_73.md) |
|                                                                                                         | * *                                                                                                                                                      |                         |
| *Benedictions on various occasions:* *M*. ix.                                                           |                                                                                                                                                          |                         |
|                                                                                                         | On seeing scenes of miracles: *M*. ix. 1; *T*. vii. 2<sup>a</sup>                                                                                        | [74](tbr55.htm#page_74.md) |
|                                                                                                         | On seeing hosts:                                                                                                                                         | [75](tbr56.htm#page_75.md) |
|                                                                                                         | Consideration of how much is already done for us, and the duty of gratitude: *T*. vii. 2<sup>b</sup>                                                     | [75](tbr56.htm#page_75.md) |
|                                                                                                         | On seeing remarkable natural phenomena, or hearing tidings: *M*. ix. 2; *T*. vii. I, 3-5, 6<sup>b</sup>                                                  | [76](tbr57.htm#page_76.md) |
|                                                                                                         |    In a burial ground: *T*. vii. 6<sup>a</sup>                                                                                                           | [77](tbr57.htm#page_77.md) |
|                                                                                                         |    Over a new house or new tools: *M*. ix. 3 (3<sup>a</sup>)                                                                                             | [78](tbr57.htm#page_78.md) |
|                                                                                                         | Parenthesis—Concerning prayers in vain; *M*. ix. 4<sup>a</sup>, 5 (3<sup>bc</sup>); *T*. vii. 7                                                          | [78](tbr57.htm#page_78.md) |
|                                                                                                         |    An example of proper prayer for increase from land: *T*. vii. 8                                                                                       | [79](tbr59.htm#page_79.md) |
|                                                                                                         |    Benedictions needed at performing any command: *T*. vii. 9-15                                                                                         | [80](tbr59.htm#page_80.md) |
|                                                                                                         | <span id="page_xxiv">p. xxiv</span>                                                                                                                      |                         |
|                                                                                                         |                                                                                                                                                          | PAGE                    |
|                                                                                                         | Prayers on entering and leaving a town: *M*. ix. 6 (4); *T*. vii. 16                                                                                     | [82](tbr59.htm#page_82.md) |
|                                                                                                         | Or a public bath: *T*. vii. 17                                                                                                                           | [83](tbr60.htm#page_83.md) |
|                                                                                                         | Benedictions for not being a Gentile, a woman, or uneducated: *T*. vii. 18                                                                               | [84](tbr60.htm#page_84.md) |
|                                                                                                         | Benediction for evil as for good: *M*. ix. 7 (5<sup>a</sup>); *cf*. ix. 4 (3<sup>b</sup>); *cf.* *T*. vii. 7, [p. 78](tbr57.htm#page_78)                 | [85](tbr60.htm#page_85.md) |
|                                                                                                         | Against irreverence for the Temple: *M*. ix. 8<sup>a</sup> (5<sup>b</sup>); *T*. vii. 19                                                                 | [85](tbr60.htm#page_85.md) |
|                                                                                                         | On the closing words of the Benedictions: *M*. ix. 8<sup>b</sup> (5<sup>c</sup>); *T*. vii. 21, 22                                                       | [86](tbr62.htm#page_86.md) |
|                                                                                                         | On the use of the Divine Name at the beginning and end of Benedictions: *T*. vii. 20                                                                     | [87](tbr63.htm#page_87.md) |
|                                                                                                         | Salutations in the Name: *M*. ix. 8<sup>c</sup> (5<sup>d</sup>); *T*. vii. 23, 24                                                                        | [88](tbr63.htm#page_88.md) |
|                                                                                                         | A hundred commands are performed daily: *T*. vii. 24                                                                                                     | [89](tbr64.htm#page_89.md) |
|                                                                                                         | The commands surround, like angels; *T*. vii. 25                                                                                                         | [90](tbr64.htm#page_90.md) |

------------------------------------------------------------------------

[Next: Index to the Tosephta as Arranged in this Volume](tbr09.md)
