[![](../../cdshop/ithlogo.png)](../../index.md)  
[Intangible Textual Heritage](../../index)  [Gnosticism](../index.md) 
[Index](index)  [Previous](gar59)  [Next](gar61.md) 

------------------------------------------------------------------------

[Buy this Book at
Amazon.com](https://www.amazon.com/exec/obidos/ASIN/B002BA5FIO/internetsacredte.md)

------------------------------------------------------------------------

[![](img/tease.jpg)](index.md)  
*The Gnostics and Their Remains*, by Charles William King, \[1887\], at
Intangible Textual Heritage

------------------------------------------------------------------------

### The Templars

In the second paragraph Clarkson <span id="fr_241"></span>[\*](#fn_239.md)
discovers an allusion to the Vesica Piscis, which is in truth a figure
generated by two circles intersecting at their respective centres; and
for the same reason, the secret sign of the Brethren of the
Vehme-Gerichte was the two annular links of a chain. The Egg formed by
*three* intersecting circles, contains in its upper section seven
triangles, and as many in its lower section, which are the opposing
genii of Light and Darkness. This was the *idol* which the Manichæans
were accused of worshipping on the charges brought against them by the
Popes (Clarkson, p. 20). Still more does the "Vultus Triformis" of this
Creed arrest our attention as bearing a more than accidental affinity to
the triple-faced idol, the adoration whereof was so persistently laid to
the charge of the Templars--the real meaning of which accusation

<span id="page_396">p. 396</span>

shall be investigated in its proper place. This same "tête d’un homme
monstrueuse," image of "le Dieu qui ne meurt pas," so often mentioned in
the confessions of the Knights, may be recognised beyond all mistake in
the hideous head with flaring hair and beard, and eyes wide open, as if
just severed from the body, placed upon a box inscribed **X. P. S.**,
which repeatedly occurs amongst the Rosicrucian pictures in the Diary of
Hosea Lux. This MS., the most remarkable of the kind extant, or ever
composed, written between the years 1568 and 1612, is full of mystic
drawings, beautifully done in pen and ink, which may be either prophetic
hieroglyphs, or else enshroud the *arcana* of some seeker after the
Elixir of Life: the latter it would rather seem, to judge from the
perpetual introduction of certain *very significant* emblems. The author
must have belonged (as an actual Mason assures me) to a Lodge of
Templars, as is proved by his use of the "hand in hand" and "foot to
foot" insignia. As exhibiting the whole list of the present Masonic
signs, but employed for Rosicrucian purposes, at so early a date, this
Diary is of the utmost value to the history of the Order. <span
id="fr_242"></span>[\*](#fn_240.md) To quote a few of the most important
embellishments of these mystic pages: the same "Baphometic" Head appears
in another place set on a box inscribed with "Solomon's Seal,"
containing a retort: over the head is a disk, set all round dial fashion
but with hearts instead of numerals; in the field is written the
opposite motto "Timore et tremore." Another is picture presents the Head
hovering above the Ark of the Covenant, all enclosed within the outline
of a *heart* out of whose aorta issues a naked boy bearing a flaming
star and crescent conjoined. Yet more mysterious is the heart containing
**Τ** over a bell resting upon a star: above all, for a crest is set
Solomon's Seal; for supporters to the shield, his pillars Jachin and
Boaz, flanked on the right by that King seated, on the left by a naked
man standing, who pierces the heart with a long rod. Singular, too, is
the man with uplifted hands, having instead of a face Solomon's Seal
enclosing a retort. Other symbols

<span id="page_397">p. 397</span>

frequently occurring on these pictures are the naked boy extended on the
spokes of a wheel; or again placed upon an egg set in a candlestick: the
king's bust crowned with the winged crescent (on which the merest novice
in alchemy can discern the allusion to *regulus* of antimony and
*quicksilver*): the egg containing a circle whence issue rays of light;
probably typifying the *crucible*, for another heading shows the same
figure within a furnace with the infant *metal* springing rapturously
from its womb; the five links of a chain interlaced: all these being
Rosicrucian emblems now embalmed in the repertory of the Freemasons.
These drawings, besides their artistic value with respect to their
fertile invention and incredibly minute finish (Lux being a copper-plate
engraver of some eminence), are highly interesting as pictorial
exponents of the Hermetic philosophy still so flourishing at the time of
their execution. Of such designs, nothing can surpass in elaborate
execution and impenetrable mystery the large drawing of the naked female
standing upon musical notes, holding in her right a torch tipped with a
beautiful face whence issue flames; an owl perched upon her extended
left hand; on her breast for brooch Sol's head in a crescent. Upon a
pedestal is set a tall long-necked alembic containing the most obvious
emblem of the generative power, emitting upwards the stream of Life,
which is caught into the mouth of a cherub whose hair forms a bunch of
flowers supporting the before-mentioned disk of hearts, whilst his hand
holds forth a wheatsheaf. In the field lies a crown over a marshal's
bâton shaped like a phallas. Another drawing full of interest is the
portrait of a man in a fur cap with plume, wearing round his neck a
pendant inscribed like the jewel of the **G. A.**, from which again is
hung a human foot; with his right hand he points to a crescent divided
into three parts enclosing **X. A. P.**, his left rests on the head of a
mighty hammer. De Quincey, in the above quoted essay, describes a
manuscript work by Simon Stadion, of Würtemberg, written in the year
1604, under the title, "Naometria, seu nuda et prima Libri intus et
foris scripti Expositio, et Prognosticticus." It is a series of dreams
and prophecies based upon the Apocalypse: in which he speaks of "Stellæ
matutinæ ductu anno 1572 conspectæ";

<span id="page_398">p. 398</span>

and constantly brings in the Rose and Cross, on which account he is
generally supposed to have been a Rosicrucian. Martin Luther also took
for his seal the Rose and Cross; some deep religious significance, at
the time well understood, must have recommended the device to the choice
of the "Tertius Elias."

Besides these obligations to the Rosicrucians, the London Freemasons
also borrowed much of their phraseology from Lord Bacon's work, still
fresh in men's minds, in which, adopting the idea of the "House of
Wisdom," a technical term with the Arab astrologers, he proposed the
foundation of a "Solomon's House," or learned community dedicated to the
cultivation of experimental philosophy and the advancement of science.
These philosophic and royalist plotters, in order to cloak the true
nature of their proceedings, conducted, their conclaves according to the
rules prescribed by Bacon: and the same ceremonial and nomenclature they
carefully maintain to the present day.

A final and demonstrative proof of the recent and *English* origin of
Freemasonry is afforded by the dates of institution of the various
Foreign Lodges, which are by their own profession branches of the parent
Society in London. The Parisian was not founded until the year 1725, the
Madrid in 1728, and the Florentine in 1733. And yet France and Italy had
been the birthplace of the actual *art* of masonry, and the scene of the
full glory of its revival.

Another important fact remains to be noticed, the *Rosicrucians* still
subsist amongst the Parisian Freemasons as the designation for their
highest degree (to be conferred upon distinguished English visitors),
although all disclaim those mystics as being the parent stock; inasmuch
as that truth, if allowed, were utterly incompatible with their own
claim to immemorial antiquity. Nevertheless, they loudly profess to
trace their descent through the line of the Templars down from that
splendidly fabulous origin they arrogate to themselves.

But to return to Andre, and the honour Nicolai assigns him as the
creator of the immediate parent of modern Freemasonry,

<span id="page_399">p. 399</span>

certain it is that his far-famed Rosy Cross had been ages before the
regular badge of the Knights Templars. Considering how widely the Order
had spread its branches, obtained possession and affiliated to itself
multitudes both male and female amongst the laity all over Europe, it
would be a mere absurdity to believe that all its traditions were swept
away at one stroke by the suppression of the Templars in the year
1307. <span id="fr_243"></span>[\*](#fn_241.md) In fact, the Parisian
*Templiers*, as the most important division of the French Freemasons
still style themselves, pretend to have kept up the succession of Grand
Masters unbroken; nay more, to have preserved the archives of the Order
ever since that date. François I. is even reported to have burnt alive,
with a contrivance of refined cruelty in "The fiery bath," four
unfortunate gentlemen convicted of being Templars, <span
id="fr_244"></span>[†](#fn_242.md) which, if true, suffices to prove the
existence of that fraternity down to a period but little removed from
the public manifestation of the Rosicrucians. Truly was he by such
proceedings "semina odii in longum jaciens," to borrow the forcible
simile of Tacitus, if we are to believe Barruel's express declaration
that Spartacus Weishaupt's *Jacobins* did no more than pay to royalty
the so long deferred legacy of revenge handed down to them by generation
after generation of secret societies--fulfilling the last Templar's
solemn vow of vengeance against Philippe le Bel, and all future kings in
his person. By order of the same François I., his general Almeida,
extirpated with a cruelty unusual even in those times the remnant of the
Albigenses still lurking in the villages of Provence, a sect, it should
be remembered, of genuine Manichæans, transplanted thither from the East
at a comparatively recent date. As Manichæans, they would naturally have
preserved the symbols, and tokens for mutual recognition so much in
vogue, as history and existing monuments attest,

<span id="page_400">p. 400</span>

amongst all followers of the Gnosis. And such machinery and grown yet
more into articles of necessity, after continued persecution had
transformed their congregations into regular secret societies.

But dismissing all such speculations, we are under no necessity for
connecting the Rosicrucians with the ancient Brethren of the Temple, in
order to account for their display of the Gnostic symbols which figure
so conspicuously in Andreae's plates, and which have since been so
diligently illustrated (though often with erroneous ingenuity) by Von
Hammer in his 'Mystery of Baphomet Revealed;' yet even his
*misinterpreted* examples go to prove the same truth, and his
'Baphometic Idols,' whose adoration should have been the heaviest count
in the charges against the Templars (though unmistakably of Cinque-cento
design and workmanship), are astrological and cabbalistic sigils
breathing a purely *Rosicrucian* spirit in their syncretism of symbolic
forms. For there is one point in these sculptures alone sufficient to
upset all Von Hammer's elaborate structure--the Arabic legends, being
cut in current Neshki characters, betray their modern manufacture; for
had they been contemporary with the flourishing times of the Templars,
the primitive Cufic must, as a matter of course, have been employed.
Yet, at the same time, these same legends indicate clearly enough the
fountain-head of the doctrines held in common by all similar
fraternities.

But before considering this last and so important point, the subject
will be more conveniently approached by our first considering the
principal arguments set forth by the learned Orientalist in support of
his theory. His object in truth is sufficiently declared by the title of
his treatise, 'Mysterium Baphometis Revelatum: seu Fratres militiæ
Templi quà Gnostici et quidem Ophiani, apostasiæ, idololatriæ, et quidem
impuritatis convicti per ipsa eorum monumenta" (published in the *Mines
de l’Orient*, vol. vi.). The treatise is copiously illustrated with fine
copper plates of magical statuettes, architectural ornaments, mystical
inscriptions, vases, and coins. As regards *historical* evidence, the
main foundation of his hypothesis rests upon certain heads in the
Articles of Accusation against the

<span id="page_401">p. 401</span>

<span class="contnote">\[paragraph continues\]</span> Templars,
despatched by Pope Clement V. to all archbishops, &c. These are--

"*Art*. 42. Item, quod ipsi per singulas provincias habeant Idola,
videlicet *capita*, <span id="fr_245"></span>[\*](#fn_243.md) quorum aliqua
habebant *tres facies*, et alia unam, et aliqua *cranium* humanum
habebant.

"*Art*. 54. Item, quod aliquod caput illorum cingebant seu tangebant
chordulis quibus si ipsos cingebant, circa camiciam seu carnem.

"*Art*. 55. Quod in hac receptione, singulis fratribus prædictæ chordulæ
tradebantur, vel aliæ longitudinis earum."

In this girding with a consecrated string there is a striking analogy to
the *Kosti* <span id="fr_246"></span>[†](#fn_244.md) prescribed by the
Zoroastrian religion, still assumed by every Parsee upon his initiation
(which takes place upon his completing his *seventh* year), and
thenceforth constantly worn over the shirt. This distinctive badge was
the most likely of all to be retained by Manes (himself a Magian) in his
Christianised modification of the Persian creed. Other articles,
unnecessary to quote, allege the permission and even the obligation of
unnatural practices. But, from the very beginning, this last accusation,
so needless to be proved, because so readily believed, has been brought
against the members of all secret societies, as Ovid shows by the
popular tradition respecting Orpheus, the acknowledged founder of the
Grecian mysteries.

"Illetiam Thracum populis fuit auctor amorem  
 In teneros transferre mares, citraque juventam,  
 Ætatis breve ver et primos carpere flores." <span
id="fr_247"></span>[‡](#fn_245) (Metam. x. 83-85.md).

Clarkson has more recently discussed the same question in his very
ingenious essay 'Upon the Symbolical Evidence of the Temple Church. Were
the Templars Gnostic Idolaters as

<span id="page_402">p. 402</span>

alleged?' He endeavours to prove their Manicheism by means of
*architectural* evidence, deduced from the members of the edifice and
the geometrical relations discoverable in the ground plan. But,
dispassionately considered, such arguments are of little weight,
inasmuch as they could be found, if looked for (under a similar
prepossession), in many other buildings, both mediæval and modern,
having no connection whatsoever with the Brethren of the Temple. Again,
a fatal objection to his theory is the fact, that all such "Round
Churches" are acknowledged copies of the Holy Sepulchre at Jerusalem,
which, whether Helena's original building, or merely a Gothie
reconstruction by the Frankish kings (the more probable explanation),
was certainly not subjected to Templar influence in the laying out of
its plan. The circular, domical shape had been given by Helena to her
church simply because that form, according to the Roman notion handed
down from Etruscan antiquity, was regarded as most appropriate for a
*tomb*. Hence, to go no further back, it was adopted for Helena's own
sepulchre (*Torre pignatara*), and for that of her grandchild,
Constantia. In illustration of his hypothesis Clarkson adduces the
statement of Clemens Alexandrinus about the "Primary Elements" of the
old Egyptians, and *supposes* them to have been the *square*, the
*angle*, the *semicircle*, the *circle*, the *oval*, the *line*, the
*waved line*, *triangular*, and *the cross*. These would represent the
seven primary consonants, of which the invention was attributed to
Menmon, viz., the letters with their equivalent sounds, **B, C, D, L, M,
N, S**. Should this theory have any truth in it, the frequent
introduction of such figures into talismanic inscriptions obtains a
satisfactory explanation.

------------------------------------------------------------------------

### Footnotes

<span id="fn_239"></span>[395:\*](gar60.htm#fr_241.md) 'The Symbolical
Evidence of the Temple Church. Were the Templars Gnostics?'

<span id="fn_240"></span>[396:\*](gar60.htm#fr_242.md) Through the kindness
of the present owner, Mr. J. E. Hodgkin, F.S.A.; I have had opportunity
to make a minute examination of the MS.

<span id="fn_241"></span>[399:\*](gar60.htm#fr_243.md) Even the sceptical
Michelet allows "il est possible que les Templiers qui échappèrent se
soient fendus en sociétés secrètes. En Écosse ils disparaissent tous
excepté deux. Or, on a remarqué que les plus secrets mystères dans la
Francmaçonnerie sont réputés émaner d’Écosse, et que les hauts grades y
sont nommes Écossais. V. Grouvelle et les écrivains qu’il a
suivis.'--('Hist. de France,' iii. p. 129.)

<span id="fn_242"></span>[399:†](gar60.htm#fr_244.md) Communicated to me by
a Brother; the historical authority I cannot discover.

<span id="fn_243"></span>[401:\*](gar60.htm#fr_245.md) Such a head of
silver was actually seized in the Parisian Chapter-house; but the
Templars passed it off for a reliquary containing the skull of one of
the 11,000 virgins, in spite of the long beard with which it was
furnished (Rayn. p. 299). Another is said to have been found elsewhere
bearing the numeral **LIII**. These damning evidences would naturally
have been made away with by the Templars upon the first alarm of the
inquiry.

<span id="fn_244"></span>[401:†](gar60.htm#fr_246.md) Woven out of *seven*
threads by the wife of the *Mobed* or fire-priest.

<span id="fn_245"></span>[401:‡](gar60.htm#fr_247.md) "Dum erat juvenis
sæcularis, omnes pueri clamabant publice et vulgariter unus ad alterum,
Custodiatis vobis ab osculo Templariorum" Wilkins, *Conc. Britann.* ii.
p. 360).

------------------------------------------------------------------------

[Next: Idols of Baphomet](gar61.md)
