[Sacred-Texts](../../index) [African](../index.md)

------------------------------------------------------------------------

Yoruba Legends

by M. I. Ogumefu, B.A.

\[London, 1929\]

------------------------------------------------------------------------

[Title Page](yl00.md)  
[PREFACE](yl01.md)  
[CONTENTS](yl02.md)  
[I THE KINGDOM OF THE YORUBAS](yl03.md)  
[II HOW TRIBAL MARKS CAME TO BE USED](yl04.md)  
[III AKITI THE HUNTER](yl05.md)  
[IV SONS OF STICKS](yl06.md)  
[V WHY WOMEN HAVE LONG HAIR](yl07.md)  
[VI WHY PEOPLE CRY “LONG LIVE THE KING!” WHEN THUNDER FOLLOWS
LIGHTNING](yl08.md)  
[VII THE OL<u>O</u>FIN AND THE MICE](yl09.md)  
[VIII THE IROKO TREE](yl10.md)  
[IX ORISA OKO](yl11.md)  
[X MOREMI](yl12.md)  
[XI THE BAT](yl13.md)  
[XII THE LEOPARD-MAN](yl14.md)  
[XIII THE WATER-BIRD](yl15.md)  
[XIV THE ANTS AND THE TREASURE](yl16.md)  
[XV THE VOICES OF BIRDS](yl17.md)  
[XVI THE THREE MAGICIANS](yl18.md)  
[XVII ISOKUN AND THE BABY](yl19.md)  
[XVIII THE TWIN BROTHERS](yl20.md)  
[XIX HOW LEOPARD GOT HIS SPOTS](yl21.md)  
[XX ANOTHER STORY OF LEOPARD’S SPOTS](yl22.md)  
[XXI THE HEAD](yl23.md)  
[XXII OLE AND THE ANTS](yl24.md)  
[XXIII THE BOA-CONSTRICTOR](yl25.md)  
[XXIV OLURONBI](yl26.md)  
[XXV THE STAFF OF ORANYAN](yl27.md)  
[XXVI THE ELEPHANT’S TRUNK](yl28.md)  
[XXVII THE SECRET OF THE FISHING-BASKETS](yl29.md)  
[XXVIII THE TEN GOLDSMITHS](yl30.md)  
[XXIX THE COOKING-POT](yl31.md)  
[XXX THE PARROT](yl32.md)  
[XXXI THE GHOST-CATCHER](yl33.md)  
[STORIES OF TORTOISE](yl34.md)  
[XXXII TORTOISE AND THE KING](yl35.md)  
[XXXIII TORTOISE AND MR. FLY](yl36.md)  
[XXXIV ERIN AND ERINOMI (THE LAND- AND WATER-ELEPHANTS)](yl37.md)  
[XXXV THE THREE DEATHS OF TORTOISE](yl38.md)  
[XXXVI TORTOISE AND THE COCK](yl39.md)  
[XXXVII TORTOISE AND CRAB](yl40.md)  
[XXXVIII TORTOISE AND PIGEON](yl41.md)  
[XXXIX TORTOISE AND THE WHIP-TREE](yl42.md)  
[XL TORTOISE AND THE RAIN](yl43.md)  
