<div class="filenav">

[![](../../cdshop/ithlogo.png)](../../index.md)  
[Intangible Textual Heritage](../../index)  [Islam](../index.md)   
[Hypertext Quran](../htq/index)  [Unicode Quran](../uq/index.md) 
[Pickthall](../pick/index)  [Palmer Part I (SBE06)](../sbe06/index.md) 
[Yusuf Ali/Arabic](../quran/index)  [Yusuf Ali English](../yaq/index.md) 
[Rodwell](../qr/index.md)   

</div>

------------------------------------------------------------------------

# THE QUR’ÂN

#### E.H. Palmer

### Part II: XVII-CXIV

Sacred Books of the East, Vol. 9

#### \[1880\]

------------------------------------------------------------------------

[Part I](../sbe06/index.md)   \|   **Part II**

------------------------------------------------------------------------

[Title Page](sbe0900.md)  
[Contents](sbe0901.md)  
[XVII. The Chapter of the Night Journey](017.md)  
[XVIII. The Chapter of the Cave](018.md)  
[XIX. The Chapter of Mary](019.md)  
[XX. The Chapter of *T*. H.](020.md)  
[XXI. The Chapter of the Prophets](021.md)  
[XXII. The Chapter of the Pilgrimage](022.md)  
[XXIII. The Chapter of Believers](023.md)  
[XXIV. The Chapter of Light](024.md)  
[The Chapter of the Discrimination](025.md)  
[XXVI. The Chapter of the Poets](026.md)  
[XXVII. The Chapter of the Ant](027.md)  
[XXVIII. The Chapter of the Story](028.md)  
[XXIX. The Chapter of the Spider](029.md)  
[XXX. The Chapter of the Greeks](030.md)  
[XXXI. The Chapter of Loqmân](031.md)  
[XXXII. The Chapter of Adoration](032.md)  
[XXXIII. The Chapter of the Confederates](033.md)  
[XXXIV. The Chapter of Sebâ](034.md)  
[XXXV. The Chapter of the Angels](035.md)  
[XXXVI. The Chapter of Y. S.](036.md)  
[XXXVII. The Chapter of the 'Ranged.'](037.md)  
[XXXVIII. The Chapter of S](038.md)  
[XXXIX. The Chapter of the Troops](039.md)  
[XL. The Chapter Of The Believer](040.md)  
[XLI. The Chapter 'Detailed.'](041.md)  
[XLII. The Chapter of Counsel](042.md)  
[XLIII. The Chapter of Gilding](043.md)  
[XLIV. The Chapter of Smoke](044.md)  
[XLV. The Chapter of the Kneeling](045.md)  
[XLVI. The Chapter of El A‘hqâf](046.md)  
[XLVII. The Chapter of Mohammed, Also Called Fight](047.md)  
[XLVIII. The Chapter of Victory](048.md)  
[XLIX. The Chapter of the Inner Chambers](049.md)  
[L. The Chapter of Q](050.md)  
[LI. The Chapter of the Scatterers](051.md)  
[LII. The Chapter of the Mount](052.md)  
[LIII. The Chapter of the Star](053.md)  
[LIV. The Chapter of the Moon](054.md)  
[LV. The Chapter of the Merciful](055.md)  
[LVI. The Chapter of the Inevitable](056.md)  
[LVII. The Chapter of Iron](057.md)  
[LVIII. The Chapter of the Wrangler](058.md)  
[LIX. The Chapter of the Emigration](059.md)  
[LX. The Chapter of the Tried](060.md)  
[LXI. The Chapter of the Ranks](061.md)  
[LXII. The Chapter of the Congregation](062.md)  
[LXIII. The Chapter of the Hypocrites](063.md)  
[LXIV. The Chapter of Cheating](064.md)  
[LXV. The Chapter of Divorce](065.md)  
[LXVI. The Chapter of Prohibition](066.md)  
[LXVII. The Chapter of the Kingdom](067.md)  
[LXVIII. The Chapter of the Pen](068.md)  
[LXIX. The Chapter of the Infallible](069.md)  
[LXX. The Chapter of the Ascents](070.md)  
[LXXI. The Chapter of Noah](071.md)  
[LXXII. The Chapter of the *G*inn](072.md)  
[LXXIII. The Chapter of the Enwrapped](073.md)  
[LXXIV. The Chapter of the 'Covered'](074.md)  
[LXXV. The Chapter of the Resurrection](075.md)  
[LXXVI. The Chapter of Man](076.md)  
[LXXVII. The Chapter of Those Sent](077.md)  
[LXXVIII. The Chapter of the Information](078.md)  
[LXXIX. The Chapter of Those Who Tear Out](079.md)  
[LXXX. The Chapter 'He Frowned.'](080.md)  
[LXXXI. The Chapter of the Folding Up](081.md)  
[LXXXII. The Chapter of the Cleaving Asunder](082.md)  
[LXXXIII. The Chapter of Those Who Give Short Weight](083.md)  
[LXXXIV. The Chapter of the Rending Asunder](084.md)  
[LXXXV. The Chapter of the Zodiacal Signs](085.md)  
[LXXXVI. The Chapter of the Night Star](086.md)  
[LXXXVII. The Chapter of the Most High](087.md)  
[LXXXVIII. The Chapter of the Overwhelming](088.md)  
[LXXXIX. The Chapter of the Dawn](089.md)  
[XC. The Chapter of the Land](090.md)  
[XCI. The Chapter of the Sun](091.md)  
[XCII. The Chapter of the Night](092.md)  
[XCIII. The Chapter of the Forenoon](093.md)  
[Chapter XCIV. The Chapter of 'Have We Not Expanded?'](094.md)  
[XCV. The Chapter of the Fig](095.md)  
[XCVI. The Chapter of Congealed Blood](096.md)  
[XCVII. The Chapter of Power](097.md)  
[XCVIII. The Chapter of the Manifest Sign](098.md)  
[XCIX. The Chapter of the Earthquake](099.md)  
[C. The Chapter of the Chargers](100.md)  
[CI. The Chapter of the Smiting](101.md)  
[CII. The Chapter of the Contention about Numbers](102.md)  
[CIII. The Chapter of the Afternoon](103.md)  
[CIV. The Chapter of the Backbiter](104.md)  
[CV. The Chapter of the Elephant](105.md)  
[CVI. The Chapter of the Qurâi*s*](106.md)  
[CVII. The Chapter Of 'Necessaries.'](107.md)  
[CVIII. The Chapter of El KâuTHar](108.md)  
[CIX. The Chapter of Misbelievers](109.md)  
[CX. The Chapter of Help](110.md)  
[CXI. The Chapter of Abu Laheb](111.md)  
[CXII. The Chapter of Unity](112.md)  
[CXIII. The Chapter of the Daybreak](113.md)  
[CXIV. The Chapter of Men](114.md)  
[Index](sbe09idx.md)  
