[![](../../../cdshop/ithlogo.png)](../../../index.md)  
[Intangible Textual Heritage](../../../index.md) 
[Christianity](../../index)  [Calvin](../index.md) 

------------------------------------------------------------------------

<table width="75%">
<colgroup>
<col style="width: 100%" />
</colgroup>
<tbody>
<tr class="odd">
<td width="50%" data-valign="TOP"><h1 id="the-institutes-of-the-christian-religion" data-align="CENTER">The Institutes of the Christian Religion</h1>
<h2 id="by-john-calvin" data-align="CENTER">by John Calvin</h2>
<h3 id="tr.-by-henry-beveridge" data-align="CENTER">tr. by Henry Beveridge</h3>
<h4 id="section" data-align="CENTER">[1845]</h4></td>
</tr>
</tbody>
</table>

------------------------------------------------------------------------

[Contents](#contents)    [Start Reading](inst000.md)

------------------------------------------------------------------------

<span id="contents"></span> <span id="section_000"></span>

### Title Page

[Title Page](inst000.md)  
<span id="section_001"></span>

### Prefaces

[Prefaces](inst001.md)  
[PREFACE TO THE ELECTRONIC EDITION.](inst002.md)  
[INTRODUCTION](inst003.md)  
[THE PRINTERS TO THE READERS.](inst004.md)  
[THE ORIGINAL TRANSLATORS PREFACE.](inst005.md)  
[PREFATORY ADDRESS TO HIS MOST CHRISTIAN MAJESTY, THE MOST MIGHTY AND
ILLUSTRIOUS MONARCH, FRANCIS, KING OF THE FRENCH, HIS
SOVEREIGN](inst006.md)  
[THE EPISTLE TO THE READER](inst007.md)  
[SUBJECT OF THE PRESENT WORK](inst008.md)  
[EPISTLE TO THE READER.](inst009.md)  
[METHOD AND ARRANGEMENT,OR SUBJECT OF THE WHOLE WORK.](inst010.md)  
<span id="section_002"></span>

### GENERAL INDEX OF CHAPTERS.

[GENERAL INDEX OF CHAPTERS.](inst011.md)  
<span id="section_003"></span>

### INSTITUTES OF THE CHRISTIAN RELIGION

[INSTITUTES OF THE CHRISTIAN RELIGION](inst012.md)  
[BOOK FIRST. - OF THE KNOWLEDGE OF GOD THE CREATOR](inst013.md)  
[ARGUMENT.](inst014.md)  
[CHAPTER 1. - THE KNOWLEDGE OF GOD AND OF OURSELVES MUTUALLY CONNECTED.
NATURE OF THE CONNECTION.](inst015.md)  
[CHAPTER 2. - WHAT IT IS TO KNOW GOD,TENDENCY OF THIS
KNOWLEDGE.](inst016.md)  
[CHAPTER 3. - THE KNOWLEDGE OF GOD NATURALLY IMPLANTED IN THE HUMAN
MIND.](inst017.md)  
[CHAPTER 4. - THE KNOWLEDGE OF GOD STIFLED OR CORRUPTED, IGNORANTLY OR
MALICIOUSLY.](inst018.md)  
[CHAPTER 5. - THE KNOWLEDGE OF GOD CONSPICUOUS IN THE CREATION, AND
CONTINUAL GOVERNMENT OF THE WORLD.](inst019.md)  
[CHAPTER 6. - THE NEED OF SCRIPTURE, AS A GUIDE AND TEACHER, IN COMING
TO GOD AS A CREATOR](inst020.md)  
[CHAPTER 7. - THE TESTIMONY OF THE SPIRIT NECESSARY TO GIVE FULL
AUTHORITY TO SCRIPTURE. THE IMPIETY OF PRETENDING THAT THE CREDIBILITY
OF SCRIPTURE DEPENDS ON THE JUDGMENT OF THE CHURCH.](inst021.md)  
[CHAPTER 8. - THE CREDIBILITY OF SCRIPTURE SUFFICIENTLY PROVED IN SO FAR
AS NATURAL REASON ADMITS.](inst022.md)  
[CHAPTER 9. - ALL THE PRINCIPLES OF PIETY SUBVERTED BY FANATICS, WHO
SUBSTITUTE REVELATIONS FOR SCRIPTURE.](inst023.md)  
[CHAPTER 10. - IN SCRIPTURE, THE TRUE GOD OPPOSED, EXCLUSIVELY, TO ALL
THE GODS OF THE HEATHEN.](inst024.md)  
[CHAPTER 11. - IMPIETY OF ATTRIBUTING A VISIBLE FORM TO GOD.THE SETTING
UP OF IDOLS A DEFECTION FROM THE TRUE GOD.](inst025.md)  
[CHAPTER 12. - GOD DISTINGUISHED FROM IDOLS, THAT HE MAY BE THE
EXCLUSIVE OBJECT OF WORSHIP.](inst026.md)  
[CHAPTER 13. - THE UNITY OF THE DIVINE ESSENCE IN THREE PERSONS TAUGHT,
IN SCRIPTURE, FROM THE FOUNDATION OF THE WORLD.](inst027.md)  
[CHAPTER 14. - IN THE CREATION OF THE WORLD, AND ALL THINGS IN IT, THE
TRUE GOD DISTINGUISHED BY CERTAIN MARKS FROM FICTITIOUS
GODS.](inst028.md)  
[CHAPTER 15. - STATE IN WHICH MAN WAS CREATED. THE FACULTIES OF THE
SOULTHE IMAGE OF GODFREE WILLORIGINAL RIGHTEOUSNESS](inst029.md)  
[CHAPTER 16. - THE WORLD, CREATED BY GOD, STILL CHERISHED AND PROTECTED
BY HIM. EACH AND ALL OF ITS PARTS GOVERNED BY HIS
PROVIDENCE.](inst030.md)  
[CHAPTER 17. - USE TO BE MADE OF THE DOCTRINE OF PROVIDENCE.](inst031.md)  
[CHAPTER 18. - THE INSTRUMENTALITY OF THE WICKED EMPLOYED BY GOD, WHILE
HE CONTINUES FREE FROM EVERY TAINT](inst032.md)  
[BOOK SECOND. - OF THE KNOWLEDGE OF GOD THE REDEEMER, IN CHRIST, AS
FIRST MANIFESTED TO THE FATHERS, UNDER THE LAW, AND THEREAFTER TO US
UNDER THE GOSPEL.](inst033.md)  
[ARGUMENT.](inst034.md)  
[CHAPTER 1. - THROUGH THE FALL AND REVOLT OF ADAM, THE WHOLE HUMAN RACE
MADE ACCURSED AND DEGENERATE. OF ORIGINAL SIN.](inst035.md)  
[CHAPTER 2. - MAN NOW DEPRIVED OF FREEDOM OF WILL, AND MISERABLY
ENSLAVED.](inst036.md)  
[CHAPTER 3. - EVERY THING PROCEEDING FROM THE CORRUPT NATURE OF MAN
DAMNABLE.](inst037.md)  
[CHAPTER 4. - HOW GOD WORKS IN THE HEARTS OF MEN.](inst038.md)  
[CHAPTER 5. - THE ARGUMENTS USUALLY ALLEGED IN SUPPORT OF FREE WILL
REFUTED.](inst039.md)  
[CHAPTER 6. - REDEMPTION FOR MAN LOST TO BE SOUGHT IN
CHRIST.](inst040.md)  
[CHAPTER 7. - THE LAW GIVEN, NOT TO RETAIN A PEOPLE FOR ITSELF, BUT TO
KEEP ALIVE THE HOPE OF SALVATION IN CHRIST UNTIL HIS ADVENT.](inst041.md)  
[CHAPTER 8. - EXPOSITION OF THE MORAL LAW.](inst042.md)  
[CHAPTER 9. - CHRIST, THOUGH KNOWN TO THE JEWS UNDER THE LAW, YET ONLY
MANIFESTED UNDER THE GOSPEL.](inst043.md)  
[CHAPTER 10. - THE RESEMBLANCE BETWEEN THE OLD TESTAMENT AND THE
NEW.](inst044.md)  
[CHAPTER 11. - THE DIFFERENCE BETWEEN THE TWO TESTAMENTS.](inst045.md)  
[CHAPTER 12. - CHRIST, TO PERFORM THE OFFICE OF MEDIATOR, BEHOVED TO
BECOME MAN.](inst046.md)  
[CHAPTER 13. - CHRIST CLOTHED WITH THE TRUE SUBSTANCE OF HUMAN
NATURE.](inst047.md)  
[CHAPTER 14. - HOW TWO NATURES CONSTITUTE THE PERSON OF THE
MEDIATOR.](inst048.md)  
[CHAPTER 15. - THREE THINGS BRIEFLY TO BE REGARDED IN CHRISTVIZ. HIS
OFFICES OF PROPHET, KING, AND PRIEST.](inst049.md)  
[CHAPTER 16. - HOW CHRIST PERFORMED THE OFFICE OF REDEEMER IN PROCURING
OUR SALVATION. THE DEATH, RESURRECTION, AND ASCENSION OF
CHRIST.](inst050.md)  
[CHAPTER 17. - CHRIST RIGHTLY AND PROPERLY SAID TO HAVE MERITED GRACE
AND SALVATION FOR US.](inst051.md)  
[BOOK THIRD. - THE MODE OF OBTAINING THE GRACE OF CHRIST. THE BENEFITS
IT CONFERS, AND THE EFFECTS RESULTING FROM IT.](inst052.md)  
[ARGUMENT.](inst053.md)  
[CHAPTER 1. - THE BENEFITS OF CHRIST MADE AVAILABLE TO US BY THE SECRET
OPERATION OF THE SPIRIT.](inst054.md)  
[CHAPTER 2. - OF FAITH. THE DEFINITION OF IT. ITS PECULIAR
PROPERTIES.](inst055.md)  
[CHAPTER 3. - REGENERATION BY FAITH. OF REPENTANCE.](inst056.md)  
[CHAPTER 4. - PENITENCE, AS EXPLAINED IN THE SOPHISTICAL JARGON OF THE
SCHOOLMEN, WIDELY DIFFERENT FROM THE PURITY REQUIRED BY THE GOSPEL. OF
CONFESSION AND SATISFACTION.](inst057.md)  
[CHAPTER 5. - OF THE MODES OF SUPPLEMENTING SATISFACTIONVIZ.
INDULGENCES AND PURGATORY.](inst058.md)  
[CHAPTER 6. - THE LIFE OF A CHRISTIAN MAN. SCRIPTURAL ARGUMENTS
EXHORTING TO IT.](inst059.md)  
[CHAPTER 7. - A SUMMARY OF THE CHRISTIAN LIFE. OF
SELF-DENIAL.](inst060.md)  
[CHAPTER 8. - OF BEARING THE CROSSONE BRANCH OF
SELF-DENIAL.](inst061.md)  
[CHAPTER 9. - OF MEDITATING ON THE FUTURE LIFE.](inst062.md)  
[CHAPTER 10. - HOW TO USE THE PRESENT LIFE, AND THE COMFORTS OF
IT.](inst063.md)  
[CHAPTER 11. - OF JUSTIFICATION BY FAITH. BOTH THE NAME AND THE REALITY
DEFINED.](inst064.md)  
[CHAPTER 12. - NECESSITY OF CONTEMPLATING THE JUDGMENT-SEAT OF GOD, IN
ORDER TO BE SERIOUSLY CONVINCED OF THE DOCTRINE OF GRATUITOUS
JUSTIFICATION.](inst065.md)  
[CHAPTER 13. - TWO THINGS TO BE OBSERVED IN GRATUITOUS
JUSTIFICATION.](inst066.md)  
[CHAPTER 14. - THE BEGINNING OF JUSTIFICATION. IN WHAT SENSE
PROGRESSIVE.](inst067.md)  
[CHAPTER 15. - THE BOASTED MERIT OF WORKS SUBVERSIVE BOTH OF THE GLORY
OF GOD, IN BESTOWING RIGHTEOUSNESS, AND OF THE CERTAINTY OF
SALVATION.](inst068.md)  
[CHAPTER 16. - REFUTATION OF THE CALUMNIES BY WHICH IT IS ATTEMPTED TO
THROW ODIUM ON THIS DOCTRINE.](inst069.md)  
[CHAPTER 17. - THE PROMISES OF THE LAW AND THE GOSPEL
RECONCILED.](inst070.md)  
[CHAPTER 18. - THE RIGHTEOUSNESS OF WORKS IMPROPERLY INFERRED FROM
REWARDS.](inst071.md)  
[CHAPTER 19. - OF CHRISTIAN LIBERTY.](inst072.md)  
[CHAPTER 20. - OF PRAYERA PERPETUAL EXERCISE OF FAITH. THE DAILY
BENEFITS DERIVED FROM IT.](inst073.md)  
[CHAPTER 21. - OF THE ETERNAL ELECTION, BY WHICH GOD HAS PREDESTINATED
SOME TO SALVATION, AND OTHERS TO DESTRUCTION.](inst074.md)  
[CHAPTER 22. - THIS DOCTRINE CONFIRMED BY PROOFS FROM
SCRIPTURE.](inst075.md)  
[CHAPTER 23. - REFUTATION OF THE CALUMNIES BY WHICH THIS DOCTRINE IS
ALWAYS UNJUSTLY ASSAILED.](inst076.md)  
[CHAPTER 24. - ELECTION CONFIRMED BY THE CALLING OF GOD. THE REPROBATE
BRING UPON THEMSELVES THE RIGHTEOUS DESTRUCTION TO WHICH THEY ARE
DOOMED.](inst077.md)  
[CHAPTER 25. - OF THE LAST RESURRECTION.](inst078.md)  
[BOOK FOURTH. - OF THE HOLY CATHOLIC CHURCH](inst079.md)  
[ARGUMENT.](inst080.md)  
[CHAPTER 1. - OF THE TRUE CHURCH. DUTY OF CULTIVATING UNITY WITH HER, AS
THE MOTHER OF ALL THE GODLY.](inst081.md)  
[CHAPTER 2. - COMPARISON BETWEEN THE FALSE CHURCH AND THE
TRUE.](inst082.md)  
[CHAPTER 3. - OF THE TEACHERS AND MINISTERS OF THE CHURCH. THEIR
ELECTION AND OFFICE.](inst083.md)  
[CHAPTER 4. - OF THE STATE OF THE PRIMITIVE CHURCH, AND THE MODE OF
GOVERNMENT IN USE BEFORE THE PAPACY.](inst084.md)  
[CHAPTER 5. - THE ANCIENT FORM OF GOVERNMENT UTTERLY CORRUPTED BY THE
TYRANNY OF THE PAPACY.](inst085.md)  
[CHAPTER 6. - OF THE PRIMACY OF THE ROMISH SEE.](inst086.md)  
[CHAPTER 7. - OF THE BEGINNING AND RISE OF THE ROMISH PAPACY, TILL IT
ATTAINED A HEIGHT BY WHICH THE LIBERTY OF THE CHURCH WAS DESTROYED, AND
ALL TRUE RULE OVERTHROWN.](inst087.md)  
[CHAPTER 8. - OF THE POWER OF THE CHURCH IN ARTICLES OF FAITH. THE
UNBRIDLED LICENCE OF THE PAPAL CHURCH IN DESTROYING PURITY OF
DOCTRINE.](inst088.md)  
[CHAPTER 9. - OF COUNCILS AND THEIR AUTHORITY](inst089.md)  
[CHAPTER 10. - OF THE POWER OF MAKING LAWS. THE CRUELTY OF THE POPE AND
HIS ADHERENTS, IN THIS RESPECT, IN TYRANNICALLY OPPRESSING AND
DESTROYING SOULS.](inst090.md)  
[CHAPTER 11. - OF THE JURISDICTION OF THE CHURCH, AND THE ABUSES OF IT,
AS EXEMPLIFIED IN THE PAPACY.](inst091.md)  
[CHAPTER 12. - OF THE DISCIPLINE OF THE CHURCH, AND ITS PRINCIPAL USE IN
CENSURES AND EXCOMMUNICATION.](inst092.md)  
[CHAPTER 13. - OF VOWS. THE MISERABLE ENTANGLEMENTS CAUSED BY VOWING
RASHLY.](inst093.md)  
[CHAPTER 14. - OF THE SACRAMENTS.](inst094.md)  
[CHAPTER 15. - OF BAPTISM.](inst095.md)  
[CHAPTER 16. - PÆDOBAPTISM. ITS ACCORDANCE WITH THE INSTITUTION OF
CHRIST, AND THE NATURE OF THE SIGN.](inst096.md)  
[CHAPTER 17. - OF THE LORDS SUPPER, AND THE BENEFITS CONFERRED BY
IT](inst097.md)  
[CHAPTER 18 - OF THE POPISH MASS. HOW IT NOT ONLY PROFANES, BUT
ANNIHILATES THE LORDS SUPPER.](inst098.md)  
[CHAPTER 19. - OF THE FIVE SACRAMENTS, FALSELY SO CALLED. THEIR
SPURIOUSNESS PROVED, AND THEIR TRUE CHARACTER EXPLAINED.](inst099.md)  
[CHAPTER 20. - OF CIVIL GOVERNMENT.](inst100.md)  
<span id="section_004"></span>

### ONE HUNDRED APHORISMS,

[ONE HUNDRED APHORISMS,](inst101.md)  
[BOOK 1](inst102.md)  
[BOOK 2](inst103.md)  
[BOOK 3](inst104.md)  
[BOOK 4](inst105.md)  
<span id="section_005"></span>

### Indexes

[Indexes](inst106.md)  
[Index of Scripture References](inst107.md)  
