[Intangible Textual Heritage](../../../index)  [UFOs](../../index.md) 
[Mars](../index)  [Index](index)  [Previous](mah01)  [Next](mah03.md) 

------------------------------------------------------------------------

# CONTENTS

|               |                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|---------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Chapter I     | EROS URIDES, of the City of Urid, planet Mars, the Author, introduces himself and his book THE PLANET MARS AND ITS INHABITANTS.                                                                                                                                                                                                                                                                                                          |
| Chapter II    | He describes the Population Centers, Temperatures and Climate. The whole Planet is gridironed with Canals. (See Diagram.)                                                                                                                                                                                                                                                                                                                |
| Chapter III   | He gives a full description of the marvelous Martian Canal System.                                                                                                                                                                                                                                                                                                                                                                       |
| Chapter IV    | Planetary Economy. No Worries, and the Wants of all are supplied by the Commonwealth.                                                                                                                                                                                                                                                                                                                                                    |
| Chapter V     | Property and Property Rights. God, the Creator of it, is considered the Owner of all Property. Material things to the Martians are but Expedients. The Millions of Martians live as one great family, though divided into families. And it is this solidarity and filial consideration towards each other that made the stupendous Canal and other Works possible.                                                                       |
| Chapter VI    | Trade and Barter are unknown. Transportation is by Flying Ships, and Gravitational Pull has been overcome. Also, they use Cosmic or Universal Energy. All Distribution is from immense Warehouses.                                                                                                                                                                                                                                       |
| Chapter VII   | A great many Clairvoyant Visions were seen by the Shorthand Recorder, which make most interesting reading.                                                                                                                                                                                                                                                                                                                               |
| Chapter VIII  | Knowledge of God comes from within. Selfishness has been eliminated; and the Martians require no Policemen, Watchmen or other Guardians of the Peace. Christ is known to the Martians as one of the great Powers in the Universe.                                                                                                                                                                                                        |
| Chapter IX    | Mars has no Political System; yet it is controlled by the very Acme of System. Each Individual of their vast population is guided by "The Light Within" and by "LOVE."                                                                                                                                                                                                                                                                   |
| Chapter X     | Mars is ruled by LOVE, their only law. There is no Evil, for all are Good; all are Equal. Truth is simple. The people of Mars are ready to stimulate the living of the Christ-Life on other Planets. (This is a wonderful and most Inspiring chapter.)                                                                                                                                                                                   |
| Chapter XI    | Education and Training of the Individual. They have a Spoken and a Written Language; but Telepathy is often used. Set Rules of Discipline are not required. There are References to Jupiter, Neptune, Uranus, Venus, Mercury, and the two Moons of Mars.                                                                                                                                                                                 |
| Chapter XII   | Education and Training of the Individual (contd). Vocational Determination. School Age. Marriage. Science and Domestic Science. Relativity of Time, Space, Motion and Matter. All in the whole Universe is ETERNAL MOTION.                                                                                                                                                                                                               |
| Chapter XIII  | Music is an Expression of the Father. "All around us is a beautiful RAINBOW UNIVERSE". About Music of the Spheres, and that Singing is highly developed.                                                                                                                                                                                                                                                                                 |
| Chapter XIV   | Aeronautics. Inhabited Planets. Sectarianism. No Sound, no Discordant Vibrations disturb the Atmosphere of Mars.                                                                                                                                                                                                                                                                                                                         |
| Chapter XV    | Life is an Attribute of the entire Universe. The Planet Jupiter is enveloped in deep gloom and Darkness. Gives much information. Vesta, an Asteroid, is about 500 miles in diameter. Says that communications between Planets of our Solar System and our Earth will soon be realized, and that the initial Message will be from Mars. It will herald a New Era for the people of Earth, and will break down our narrow-minded Theology. |
| Chapter XVI   | The Risen Christ. All the Mars people have lived on other Planets before, except your Earth. On Mars they live the Christ-Life every day. 10,000 years ago the Mars people accepted Christ as their Savior WITHOUT MURDER.                                                                                                                                                                                                               |
| Chapter XVII  | Physical Environment is the result of Spiritual Causes, and is the Result of our Mental Attitude.                                                                                                                                                                                                                                                                                                                                        |
| Chapter XVIII | Material Life is a Lesson, and is necessary for the unfolding of Character. The Martians have mastered their Natural Passions.                                                                                                                                                                                                                                                                                                           |
| Chapter XIX   | Eros gives a graphic Description of a Martian Home and Surroundings, then shows how the Food is manipulated. It is brought from a Central Depot in a Mechanical Contrivance which is run underground, thence up into the Dining room. The Soiled Dishes are run down and off the same way. No Drudgery for the Housewife!                                                                                                                |
| Chapter XX    | "ART." The Martians have beautiful productions in Painting, Sculpture and Tapestries, some of which depict the Scenes and Episodes incident on Christ's Visit to Mars ten thousand years ago.                                                                                                                                                                                                                                            |
| Chapter XI    | Eros Urides has a good deal to write on the subject of "Scientific Sophistry," which has mostly to do with our Earth.                                                                                                                                                                                                                                                                                                                    |

 

------------------------------------------------------------------------

[Next: Foreword](mah03.md)
