[![](../../cdshop/ithlogo.png)](../../index.md)  
[Intangible Textual Heritage](../../index)  [Grimoires](../index.md) 

------------------------------------------------------------------------

# The Seventh Book of Moses

### by Johann Scheibel \[1736-1809\]

#### published in Stuttgart, Germany \[1849\]

See Also [The Sixth Book of Moses](../moses6/index.md)

------------------------------------------------------------------------

[Title Page](m700.md)

[The Twelve Tables of the Spirits](m701.md)

[THE FIRST TABLE OF THE SPIRITS OF THE AIR](m702.md)

[THE SECOND TABLE OF THE SPIRITS OF FIRE](m703.md)

[THE THIRD TABLE OF THE SPIRITS OF WATER](m704.md)

[THE FOURTH TABLE OF THE SPIRITS OF THE EARTH](m705.md)

[THE FIFTH TABLE OF SATURN](m706.md)

[THE SIXTH TABLE OF JUPITER](m707.md)

[THE SEVENTH TABLE OF MARS](m708.md)

[THE EIGHTH TABLE OF THE SUN](m709.md)

[THE NINTH TABLE OF VENUS](m710.md)

[THE TENTH TABLE OF MERCURY](m711.md)

[THE ELEVENTH TABLE OF THE SPIRITS](m712.md)

[THE TWELFTH TABLE OF THE SCHEMHAMFORASCH](m713.md)

[THE MINISTERING FORMULAS OR MYSTERIES](m714.md)

[GENERATION SEAL](m715.md)

[Extract from the Magical Kabala](m716.md)

[BREASTPLATE OF MOSES](m717.md)

[HELMET OF MOSES AND AARON](m718.md)

[BREASTPLATE OF AARON](m719.md)

[MAGICAL LAW OF MOSES](m720.md)

[THE INSCRIPTION ON THE CHALICE OF HOLINESS](m721.md)

[CONJURATION OF ELEAZAR, THE SON OF AARON](m722.md)

[DISMISSION OF ELEAZAR, THE SON OF AARON](m723.md)

[CITATION OF GERMUTHSAI OR LEVIATHAN](m724.md)

[DISMISSION OF LEVIATHAN](m725.md)

[BALAAM'S SORCERY](m726.md)

[EGYPT](m727.md)

[CONJURATION OF THE LAWS OF MOSES](m728.md)

[GENERAL CITATION OF MOSES ON ALL SPIRITS](m729.md)

[DISMISSION OF MOSES](m730.md)

[GENERAL CITATION OF MOSES ON ALL SPIRITS](m731.md)

[CHARACTERS ON THE LEFT SIDE OF THE ARK OF THE COVENANT OF THE MOST
HIGH](m732.md)

[CHARACTERS ON THE RIGHT SIDE OF THE ARK OF THE COVENANT OF THE MOST
HIGH](m733.md)

[CONJURED SPIRIT APPEARS ON A PILLAR OF FIRE](m734.md)

[CONJURED SPIRIT APPEARS ON A PILLAR OF CLOUDS](m735.md)

[Appendix to the General Citation of Moses on All Spirits](m736.md)

[THREE NEW SIGNS WITH FROGS, LICE AND PESTILENCE](m737.md)

[THREE NEW SIGNS WITH CATTLE, PESTILENCE, BLACK SMALLPOX AND HAIL](m738.md)

[SIGNS OF GRASSHOPPERS AND DARKNESS](m739.md)

[THE SPIRIT APPEARS IN THE BURNING BUSH](m740.md)

[MOSES CHANGES THE STAFF INTO A SERPENT](m741.md)

[MOSES CHANGES WATER INTO BLOOD](m742.md)

[EXTRACT FROM THE TRUE CLAVICULA OF SOLOMON AND THE GIRDLE OF
AARON](m743.md)

[PRINCIPAL CITATION ON ALL MINISTERING SPIRITS OF THE AIR AND OF EARTH,
THE LIKE OF WHICH MANASSES AND SOLOMON USED AS THE TRUE KEY SOLOMONIS
REGIS ISRAEL](m744.md)

[Treatise Sion](m745.md)

[TRANSLATOR'S PREFACE.](m746.md)

[The Vestibule of Entrance](m747.md)

[LAWS OF ENTRANCE](m748.md)

[TREATISE OF THE SIXTH BOOK OF MOSES](m749.md)

[CHAPTER I. THE SPIRIT APPEARS UNTO MOSES IN A BURNING BUSH](m750.md)

[CHAPTER II. MOSES CHANGES THE STAFF INTO A SERPENT](m751.md)

[CHAPTER III. MOSES CHANGES WATER INTO BLOOD](m752.md)

[CHAPTER IV. THREE NEW SIGNS WITH FROGS, MICE, LICE AND SIMILAR
VERMIN](m753.md)

[CHAPTER V. THREE SIGNS OF CATTLE PESTILENCE, BLACK SMALL POX AND
HAIL](m754.md)

[CHAPTER VI. THREE SIGNS WITH GRASSHOPPERS AND DARKNESS](m755.md)

[CHAPTER VII. GENERAL CITATION OF MOSES ON ALL SPIRITS](m756.md)

[THE PENTAGON OR OMNIPOTENT FIVE CORNERS](m757.md)

[TREATISE OF THE SEVENTH BOOK OF MOSES](m758.md)

[CHAPTER I. THE SPIRIT APPEARS IN A PILLAR OF FIRE BY NIGHT](m759.md)

[CHAPTER II. THE SPIRIT APPEARS IN A PILLAR OF CLOUD BY DAY](m760.md)

[CHAPTER III. BALAAM'S SORCERY](m761.md)

[CHAPTER IV. EGYPT](m762.md)

[CHAPTER V. CONJURATION OF THE LAWS OF MOSES](m763.md)

[CHAPTER VI. GENERAL CITATION OF MOSES ON ALL SPIRITS](m764.md)

[\* CHAPTER VII. GENERAL CITATION OF MOSES ON ALL SPIRITS](m765.md)

[\* CHAPTER VII. CONJURATION OF ELEAZAR](m766.md)

[CHAPTER VIII. CITATION OF QUERNITHAY OR LEVIATHAN](m767.md)

[CHAPTER IX. MAGICAL LAWS OF MOSES](m768.md)

[CHAPTER X. HELMET OF MOSES AND AARON](m769.md)

[CHAPTER XI. BREASTPLATE OF MOSES](m770.md)

[CHAPTER XII. BREASTPLATE OF AARON](m771.md)

[CHAPTER XIII. THE CHALICE OF HOLINESS](m772.md)

[BIBLIA ARCANA MAGICA ALEXANDER](m773.md)

[CHAPTER I. THE SPIRIT APPEARS IN A BURNING BUSH](m774.md)

[CHAPTER II. MOSES CHANGES THE STAFF INTO A SERPENT](m775.md)

[CHAPTER III. MOSES CHANGES WATER INTO BLOOD](m776.md)

[CHAPTER IV. THREE NEW SIGNS WITH FROGS, LICE AND SIMILAR VERMIN](m777.md)

[CHAPTER V. THREE SIGNS OF CATTLE PESTILENCE BLACK SMALLPOX AND
HAIL](m778.md)

[CHAPTER VI. THREE SIGNS WITH GRASSHOPPERS AND LOCUSTS](m779.md)

[CHAPTER VI. GENERAL CITATION OF MOSES ON ALL SPIRITS](m780.md)

[THE PENTAGON](m781.md)

[TRADITION OF THE SEVENTH BOOK OF MOSES](m782.md)

[CHAPTER I. THE SPIRIT APPEARS IN A PILLAR OF FIRE BY NIGHT](m783.md)

[CHAPTER II. THE SPIRIT APPEARS INA PILLAR OF CLOUD BY DAY](m784.md)

[CHAPTER III. BALAAM'S SORCERY](m785.md)

[CHAPTER IV. EGYPT](m786.md)

[CHAPTER V. CONJURATION OF THE LAWS OF MOSES](m787.md)

[CHAPTER VI. GENERAL CITATION OF ALL SPIRITS](m788.md)

[DISMISSAL OF MOSES](m789.md)

[MAGICAL LAWS OF MOSES](m790.md)

[BREASTPLATE OF MOSES](m791.md)

[HELMET OF MOSES AND AARON](m792.md)

[BREASTPLATE OF AARON](m793.md)

[FOR THE LEFT HAND](m794.md)

[FOR THE RIGHT HAND](m795.md)

[CONJURATION OF ELEAZAR](m796.md)

[DISMISSAL OF ELEAZAR](m797.md)

[CITATION OF QUERMILLAM OR LEVIATHAN](m798.md)

[DISMISSAL OF QUERMILLAM OR LEVIATHAN](m799.md)

[Magical (Spirit Commado) beside the Black Raven](m7100.md)

[Instructions](m7101.md)

[Citation of the Seven Great Princes](m7102.md)

[Instructions](m7103.md)

[CITATIONS AND SEALS](m7104.md)

[Citation of Ariel](m7105.md)

[Citation of Marbuel](m7106.md)

[Citation of Mephistophilis](m7107.md)

[Citation of Barbuel](m7108.md)

[Citation of Aziabel](m7109.md)

[Citation of Anituel](m7110.md)

[THE USE OF THE SEALS](m7111.md)

[The Rabellini Table](m7112.md)
