[![](../../cdshop/ithlogo.png)](../../index.md)  
[Intangible Textual Heritage](../../index)  [Africa](../index.md) 
[Index](index)  [Previous](mlb01)  [Next](mlb03.md) 

------------------------------------------------------------------------

# CONTENTS

I. INTRODUCTORY  
II. WHERE MAN CAME FROM, AND HOS DEATH CAME  
III. LEGENDS OF THE HIGH GODS  
IV. THE HEAVEN COUNTRY AND THE HEAVEN PEOPLE  
V. MORTALS WHO HAVE ASCENDED TO HEAVEN  
VI. THE GHOSTS AND THEGHOST COUNTRY  
VII. THE AVENGER OF BLOOD  
VIII. HEROES AND DEMI-GODS  
IX. THE WAKILINDI SAGA  
X. THE STORY OF LIONGO FUOMO  
XI. THE TRICKSTERS HLAKANYANA ANDHUVEANE  
XII. THE AMAZIMU  
XIII. OF WERE-WOLVES,HALF-MEN, GNOMES, GOBLINS, AND OTHER MONSTERS  
XIV. THE SWALLOWING MONSTER  
XV. LIGHTNING, THUNDER, RAIN, AND THERAINBOW  
XVI. DOCTORS, PROPHETS, AND WITCHES  
XVII. BRER RABBIT IN AFRICA  
XVIII. LEGENDS OF THETORTOISE  
XIX STORIES OF SOME OTHERANIMALS  
XX. SOME STORIES WHICH HAVE TRAVELLED  
BIBLIOGRAPHY  
INDEX

 

------------------------------------------------------------------------

[Next: Chapter I: Introductory](mlb03.md)
